package com.tkisor.nekojs.probe;

import com.tkisor.nekojs.api.catalog.ManualDeclarationCatalogEntry;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * 输出手动声明（{@link ManualDeclarationCatalogEntry}）到 {@code @manual/index.d.ts}。
 *
 * <p>这些声明涵盖内置 {@code node:xxx} 模块（assert/fs/util/...）、脚本侧 helper 类型
 * （RecipeJsonValue、PersistentDataJS 等），以及插件通过 {@code registerTypeDocs} 注册的任意
 * {@code declare module '...'} / {@code type} / {@code interface}。
 *
 * <p>输出文件是<b>全局脚本</b>（无 top-level {@code export}/{@code import}）：其中的
 * {@code declare module 'node:fs' {...}}（ambient module augmentation）与全局 {@code type}/{@code interface}
 * 一旦被 tsc 编译（jsconfig {@code include} 含本文件）就全局生效，让 {@code require('node:fs')} 等获得补全。
 *
 * <p>不按 {@code ScriptTypePredicate} 分侧 —— 声明多余无害（客户端看到 SERVER 声明不影响）。
 */
public final class ManualDeclarationGenerator {
    private ManualDeclarationGenerator() {}

    /**
     * @param entries   manual 声明条目
     * @param outputDir {@code @manual} 目录（由调用方传入 {@code outputDir.resolve("@manual")}）
     * @return 写出的文件数（0 或 1）
     */
    public static int generate(List<ManualDeclarationCatalogEntry> entries, Path outputDir) throws IOException {
        if (entries == null || entries.isEmpty()) {
            return 0;
        }
        Files.createDirectories(outputDir);
        StringBuilder sb = new StringBuilder();
        sb.append("// Auto-generated by NekoJS probe. Manual declarations: node:xxx modules, helper types, plugin modules.\n");
        sb.append("// Do not edit; regenerate with /nekojs probe.\n\n");
        for (ManualDeclarationCatalogEntry entry : entries) {
            String decl = entry.declaration();
            if (decl == null || decl.isBlank()) {
                continue;
            }
            sb.append("// ").append(entry.id()).append('\n');
            sb.append(decl.trim()).append("\n\n");
        }
        Files.writeString(outputDir.resolve("index.d.ts"), sb.toString());
        return 1;
    }
}
