package com.tkisor.nekojs.api.catalog;

import com.tkisor.nekojs.script.ScriptType;

import java.util.List;

public final class NekoCommonManualDeclarations {
    private NekoCommonManualDeclarations() {}

    public static void register(TypeDocsRegister registry) {
        registry.registerManualDeclaration(ManualDeclarationCatalogEntry.of("nekojs.recipe-json-value", "type RecipeJsonValue = null | boolean | number | string | JsonObject | JsonArray | IngredientJS | SizedIngredientJS | ItemStack | FluidStack | FluidIngredientJS | SizedFluidIngredient;", "RecipeJsonValue boundary accepted by recipe builder/custom/path APIs.", List.of("builder.property('ingredients', [Ingredient.of('minecraft:stone')])")));
        registry.registerManualDeclaration(ManualDeclarationCatalogEntry.of("nekojs.recipe-filter", "type RecipeFilterInput = string | RecipeFilterInput[] | { mod?: string; type?: string; group?: string; id?: string; input?: unknown; output?: unknown; and?: RecipeFilterInput[]; or?: RecipeFilterInput[]; not?: RecipeFilterInput; idStartsWith?: string; idEndsWith?: string; idContains?: string; };", "Recipe filter input accepted by query/remove/replace/dump APIs.", List.of("event.remove({ output: 'minecraft:stick' })")));
        registry.registerManualDeclaration(ManualDeclarationCatalogEntry.of("nekojs.ingredient-js", "interface IngredientJS { or(ingredient: IngredientInput): IngredientJS; and(ingredient: IngredientInput): IngredientJS; except(ingredient: IngredientInput): IngredientJS; matches(value: unknown): boolean; first(): ItemStack; stacks(): ItemStack[]; withCount(count: number): SizedIngredientJS; unwrap(): Ingredient; }", "Script wrapper returned by Ingredient helper methods.", List.of("Ingredient.of('minecraft:stone').withCount(3)")));
        registry.registerManualDeclaration(ManualDeclarationCatalogEntry.of("nekojs.recipe-json-builder", "interface RecipeJsonBuilder { id(id: string): RecipeJsonBuilder; group(group: string): RecipeJsonBuilder; property(key: string, value: RecipeJsonValue): RecipeJsonBuilder; merge(value: RecipeJsonValue): RecipeJsonBuilder; removeProperty(key: string): RecipeJsonBuilder; setPath(path: string, value: RecipeJsonValue): RecipeJsonBuilder; setPaths(values: Record<string, RecipeJsonValue>): RecipeJsonBuilder; removePath(path: string): RecipeJsonBuilder; removePaths(paths: string[]): RecipeJsonBuilder; json(): JsonObject; validate(): RecipeJsonBuilder; }", "JSON-first recipe builder with RecipeJsonValue boundary.", List.of("event.builder('minecraft:crafting_shapeless').property('ingredients', [Ingredient.of('minecraft:stone')])")));
        registry.registerManualDeclaration(ManualDeclarationCatalogEntry.of(ScriptType.SERVER, "nekojs.recipe-registry-proxy", "interface RecipeRegistryProxy { namespaces(): string[]; types(namespace: string): string[]; hasNamespace(namespace: string): boolean; hasType(namespace: string, type: string): boolean; [namespace: string]: unknown; } interface RecipeEventJS extends RecipeLifecycleContext { readonly recipes: RecipeRegistryProxy; }", "Recipe namespace registry exposed as event.recipes, including typed handler introspection and raw JSON fallback namespaces.", List.of("event.recipes.namespaces()", "event.recipes.types('minecraft')", "event.recipes.mymod.custom_type({ key: 'value' })")));
        registry.registerManualDeclaration(ManualDeclarationCatalogEntry.of("nekojs.recipe-lifecycle-context", "interface RecipeLifecycleContext { ids(): string[]; count(): number; exists(id: string): boolean; getJson(id: string): string | null; setJson(id: string, json: string): void; removeById(id: string): void; dump(): string; print(): void; } interface RecipeLifecyclePlugin { beforeRecipeLoading(context: RecipeLifecycleContext): void; afterRecipes(context: RecipeLifecycleContext): void; }", "Java plugin lifecycle hook context for pre/post recipe JSON processing.", List.of("registry.beforeRecipeLoading(context -> context.print())", "registry.afterRecipes(context -> context.count())")));
        registry.registerManualDeclaration(ManualDeclarationCatalogEntry.of(ScriptType.TEST, "nekojs.test-helper", "interface NekoTestHelper { section(name: string): NekoTestHelper; pass(message?: string): NekoTestHelper; fail(message?: string): NekoTestHelper; assertTrue(condition: boolean, message?: string): NekoTestHelper; assertFalse(condition: boolean, message?: string): NekoTestHelper; assertEquals(expected: unknown, actual: unknown, message?: string): NekoTestHelper; assertNotNull(value: unknown, message?: string): NekoTestHelper; assertThrows(callback: () => unknown, message?: string): NekoTestHelper; summary(): NekoTestHelper; passed(): number; failed(): number; }", "Test helper available only in test_scripts.", List.of("Test.assertEquals(2, 1 + 1, 'math works')")));
        registry.registerManualDeclaration(ManualDeclarationCatalogEntry.of(ScriptType.TEST, "nekojs.node-test", "interface NekoNodeTestOptions { skip?: boolean | string; todo?: boolean | string; } type NekoNodeTestCallback = (context: NekoNodeTestContext) => unknown | Promise<unknown>; interface NekoNodeTestContext { name: string; diagnostic(message: string): void; test(name: string, fn: NekoNodeTestCallback): unknown; test(name: string, options: NekoNodeTestOptions, fn?: NekoNodeTestCallback): unknown; skip(message?: string): void; todo(message?: string): void; } interface NekoNodeTestRunner { (name: string, fn: NekoNodeTestCallback): unknown; (name: string, options: NekoNodeTestOptions, fn?: NekoNodeTestCallback): unknown; skip(name: string, options?: NekoNodeTestOptions, fn?: NekoNodeTestCallback): unknown; todo(name: string, options?: NekoNodeTestOptions, fn?: NekoNodeTestCallback): unknown; only: NekoNodeTestRunner; before(fn: NekoNodeTestCallback): void; after(fn: NekoNodeTestCallback): void; beforeEach(fn: NekoNodeTestCallback): void; afterEach(fn: NekoNodeTestCallback): void; describe: NekoNodeTestDescribe; it: NekoNodeTestRunner; run(): void; default: NekoNodeTestRunner; } interface NekoNodeTestDescribe { (name: string, fn: NekoNodeTestCallback): unknown; (name: string, options: NekoNodeTestOptions, fn?: NekoNodeTestCallback): unknown; skip(name: string, options?: NekoNodeTestOptions, fn?: NekoNodeTestCallback): unknown; todo(name: string, options?: NekoNodeTestOptions, fn?: NekoNodeTestCallback): unknown; only: NekoNodeTestDescribe; } declare module 'node:test' { const test: NekoNodeTestRunner; export = test; } declare module 'test' { const test: NekoNodeTestRunner; export = test; }", "TEST-only node:test lightweight runner declarations.", List.of("const test = require('node:test')", "test('math', t => t.test('child', () => {}))")));
        registry.registerManualDeclaration(ManualDeclarationCatalogEntry.of("nekojs.persistent-data-js", "interface PersistentDataJS { contains(key: string): boolean; remove(key: string): PersistentDataJS; getByte(key: string): number; getShort(key: string): number; getInt(key: string): number; getLong(key: string): number; getFloat(key: string): number; getDouble(key: string): number; getString(key: string): string; getBoolean(key: string): boolean; getByteArray(key: string): number[]; getIntArray(key: string): number[]; getLongArray(key: string): number[]; getCompound(key: string): CompoundTag; putByte(key: string, value: number): PersistentDataJS; putShort(key: string, value: number): PersistentDataJS; putInt(key: string, value: number): PersistentDataJS; putLong(key: string, value: number): PersistentDataJS; putFloat(key: string, value: number): PersistentDataJS; putDouble(key: string, value: number): PersistentDataJS; putString(key: string, value: string): PersistentDataJS; putBoolean(key: string, value: boolean): PersistentDataJS; putByteArray(key: string, value: number[]): PersistentDataJS; putIntArray(key: string, value: number[]): PersistentDataJS; putLongArray(key: string, value: number[]): PersistentDataJS; putCompound(key: string, value: CompoundTag): PersistentDataJS; copyTag(): CompoundTag; replaceTag(tag: CompoundTag): PersistentDataJS; merge(tag: CompoundTag): PersistentDataJS; clear(): PersistentDataJS; markDirty(): PersistentDataJS; sync(): PersistentDataJS; get(key: string): unknown; }", "Typed CompoundTag wrapper returned by entity/player pdata() and related helpers.", List.of("player.pdata().putInt('nekojs:hits', 1).sync()")));
        registry.registerManualDeclaration(ManualDeclarationCatalogEntry.of(ScriptType.STARTUP, "nekojs.entity-goal", "type EntityCategoryInput = 'creature' | 'monster' | 'hostile' | 'ambient' | 'water_creature' | 'watercreature' | 'water_ambient' | 'waterambient' | 'underground_water_creature' | 'undergroundwatercreature' | 'axolotls' | 'axolotl' | 'misc'; interface EntityTypeRegistryEventJS { create(id: string): EntityTypeBuilderJS; create(id: string, consumer: (builder: EntityTypeBuilderJS) => void): void; } interface EntityTypeBuilderJS { category(category: EntityCategoryInput): EntityTypeBuilderJS; size(width: number, height: number): EntityTypeBuilderJS; trackingRange(value: number): EntityTypeBuilderJS; updateInterval(value: number): EntityTypeBuilderJS; receiveVelocityUpdates(value: boolean): EntityTypeBuilderJS; fireImmune(): EntityTypeBuilderJS; noSave(): EntityTypeBuilderJS; noSummon(): EntityTypeBuilderJS; attributes(consumer: (attributes: EntityAttributeBuilderJS) => void): EntityTypeBuilderJS; goals(consumer: (goals: GoalBuilderJS) => void): EntityTypeBuilderJS; } interface EntityAttributeBuilderJS { maxHealth(value: number): EntityAttributeBuilderJS; movementSpeed(value: number): EntityAttributeBuilderJS; followRange(value: number): EntityAttributeBuilderJS; attackDamage(value: number): EntityAttributeBuilderJS; armor(value: number): EntityAttributeBuilderJS; armorToughness(value: number): EntityAttributeBuilderJS; knockbackResistance(value: number): EntityAttributeBuilderJS; } type EntityTypeInput = string | EntityType; interface GoalRegisterEventJS { forType(type: EntityTypeInput): GoalBuilderJS; forType(type: EntityTypeInput, consumer: (goals: GoalBuilderJS) => void): void; } interface GoalBuilderJS { forType(type: EntityTypeInput): GoalBuilderJS; floatInWater(priority?: number): GoalBuilderJS; randomStroll(speed: number): GoalBuilderJS; randomStroll(priority: number, speed: number): GoalBuilderJS; meleeAttack(speed: number, longMemory: boolean): GoalBuilderJS; meleeAttack(priority: number, speed: number, longMemory: boolean): GoalBuilderJS; panic(speed: number): GoalBuilderJS; panic(priority: number, speed: number): GoalBuilderJS; register(): void; }", "Startup-only scripted EntityType and vanilla goal registration declarations.", List.of("RegistryEvents.entityType(event => event.create('nekojs:test_mob', builder => builder.goals(goals => goals.floatInWater())))", "GoalEvents.register(event => event.forType('minecraft:pig', goals => goals.randomStroll(6, 0.8)))")));
    }
}
