package com.tkisor.nekojs.platform;

public enum PlatformCapability {
    TAGS,
    DATA_GENERATION,
    RESOURCE_PACKS,
    CREATIVE_TAB_MODIFY,
    CLIENT_SCREENS,
    CLIENT_KEYBINDS,
    CLIENT_RENDERERS,
    RECIPE_HOT_RELOAD,
    RECIPE_SCHEMA_AWARE,
    NETWORK_CUSTOM_CHANNEL,
    NBT_BINARY_IO,
    LOOT_MODIFICATION,
    RECIPE_VIEWER,
    REGISTRY_BLOCK_VARIANTS,
    REGISTRY_ENCHANTMENT,
    REGISTRY_POTION,
    REGISTRY_PARTICLE,
    REGISTRY_CREATIVE_TAB,
    REGISTRY_SOUND,
    REGISTRY_PAINTING,
    REGISTRY_JUKEBOX_SONG,
    REGISTRY_STAT,
    REGISTRY_POI,
    REGISTRY_VILLAGER
}
