// Auto-generated by NekoJS probe. Manual declarations: node:xxx modules, helper types, plugin modules.
// Do not edit; regenerate with /nekojs probe.

// sample-helper
declare module "@manual/sample-helper" {
    export function helperFn(input: string): string;
}

