package com.tkisor.nekojs.probe.backend.python;

import com.tkisor.nekojs.probe.backend.typescript.EventDeclarationGenerator;
import com.tkisor.nekojs.api.ScriptType;
import com.tkisor.nekojs.api.catalog.EventCatalogEntry;
import com.tkisor.nekojs.api.surface.ApiSymbolId;
import com.tkisor.nekojs.api.surface.ApiTypeRef;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.stream.Collectors;

/**
 * 事件声明渲染器：{@link EventCatalogEntry} → Python {@code .pyi}（镜像 TS {@code EventDeclarationGenerator}）。
 *
 * <p>产出 {@code nekojs/_events/<side>/__init__.pyi}：每个事件组一个类（组名 + {@code Type} 后缀，
 * 如 {@code ServerEventsType}，避免与全局绑定名冲突），类内每个事件一个 {@code @staticmethod}；
 * dispatch 型事件追加带 {@code extra} key 参数的重载（.pyi 里同名 def 即重载，与 TS 双签名一致）。
 *
 * <p>事件对象类型与 dispatch key 类型都是 best-effort：SYMBOL 未被 probe 收集 → {@code Any}；
 * dispatch key 若存在适配器输入别名（如 {@code ResourceLocation_}），用别名放宽输入。
 */
public final class PythonEventRenderer {
    private final ApiTypeRefPyRenderer typeR;
    private final Set<String> availableFqns;

    public PythonEventRenderer(ApiTypeRefPyRenderer typeR, Set<String> availableFqns) {
        this.typeR = typeR;
        this.availableFqns = availableFqns;
    }

    /**
     * @param side            目标 ScriptType（文件头注释用）
     * @param events          本 side 的事件（已按 {@code scriptType().test(side)} 过滤，非空）
     * @param adapterAliases  目标 FQN → 适配器输入别名（dispatch key 放宽用；可为 null）
     */
    public String render(ScriptType side, List<EventCatalogEntry> events,
                         Map<String, PythonProbeBackend.PyAdapterAlias> adapterAliases) {
        // 1. 收集 import（事件类型 + dispatch key 类型/别名）
        Map<String, String> importByName = new TreeMap<>(); // simpleName → fqn
        List<EventInfo> infos = new ArrayList<>();
        for (EventCatalogEntry e : events) {
            String eventType = renderClass(e.eventType(), importByName);
            String keyType = null;
            if (e.dispatchable() && e.dispatchKeyType() != null) {
                keyType = renderKey(e.dispatchKeyType(), adapterAliases, importByName);
            }
            infos.add(new EventInfo(e, eventType, keyType));
        }

        // 2. 文件头 + typing import + 跨包 import
        StringBuilder sb = new StringBuilder();
        sb.append("# Auto-generated by NekoJS probe — Python stubs for ").append(side.name).append(" events.\n");
        sb.append("# Do not edit; regenerate with `/nekojs probe python`.\n\n");
        // overload 始终引入（即使本文件没有 dispatch 事件；stub 中未使用不报错）
        sb.append("from typing import Any, Callable, overload\n");
        for (var e : importByName.entrySet()) {
            sb.append("from nekojs._java.").append(pkgOf(e.getValue())).append(" import ").append(e.getKey()).append("\n");
        }

        // 3. 按 group 分组（保持事件出现顺序）→ 每组一个 <Group>Type 类
        Map<String, List<EventInfo>> byGroup = infos.stream().collect(
                Collectors.groupingBy(i -> i.entry().group(), LinkedHashMap::new, Collectors.toList()));
        for (var groupEntry : byGroup.entrySet()) {
            sb.append("\nclass ").append(groupTypeName(groupEntry.getKey())).append(":\n");
            for (EventInfo info : groupEntry.getValue()) {
                String name = PythonClassRenderer.pyIdent(info.entry().name());
                if (info.keyType() != null) {
                    // dispatch 型事件的两个签名必须都用 @overload 声明：.pyi 里同名不同参的
                    // 裸 def 会被 Pylance/pyright 报「方法声明被同名声明遮盖」(reportRedeclaration)。
                    sb.append("    @staticmethod\n");
                    sb.append("    @overload\n");
                    sb.append("    def ").append(name)
                      .append("(handler: Callable[[").append(info.eventType()).append("], None]) -> None: ...\n");
                    sb.append("    @staticmethod\n");
                    sb.append("    @overload\n");
                    sb.append("    def ").append(name).append("(extra: ").append(info.keyType())
                      .append(", handler: Callable[[").append(info.eventType()).append("], None]) -> None: ...\n");
                } else {
                    sb.append("    @staticmethod\n");
                    sb.append("    def ").append(name)
                      .append("(handler: Callable[[").append(info.eventType()).append("], None]) -> None: ...\n");
                }
            }
        }
        return sb.toString();
    }

    /** 事件组的 Python 类名：组名 + {@code Type} 后缀（如 {@code ServerEventsType}）。 */
    static String groupTypeName(String group) {
        return PythonClassRenderer.pyIdent(group) + "Type";
    }

    /** 事件对象类型：SYMBOL 可用 → import + 简单名；否则 renderer 兜底 Any。 */
    private String renderClass(Class<?> cls, Map<String, String> importByName) {
        if (cls == null) return "Any";
        ApiTypeRef ref = classToTypeRef(cls);
        importSymbolIfAvailable(ref, importByName);
        return typeR.render(ref);
    }

    /** dispatch key 类型：有适配器别名 → 别名（放宽输入）；否则普通渲染。 */
    private String renderKey(Class<?> cls, Map<String, PythonProbeBackend.PyAdapterAlias> adapterAliases,
                             Map<String, String> importByName) {
        ApiTypeRef ref = classToTypeRef(cls);
        if (ref.kind() == ApiTypeRef.Kind.SYMBOL) {
            String fqn = ApiTypeRefPyRenderer.extractFqn(ref.name());
            PythonProbeBackend.PyAdapterAlias alias = adapterAliases == null ? null : adapterAliases.get(fqn);
            if (alias != null) {
                importByName.put(alias.aliasName(), fqn);
                return alias.aliasName();
            }
        }
        importSymbolIfAvailable(ref, importByName);
        return typeR.render(ref);
    }

    private void importSymbolIfAvailable(ApiTypeRef ref, Map<String, String> importByName) {
        if (ref == null || ref.kind() != ApiTypeRef.Kind.SYMBOL) return;
        String fqn = ApiTypeRefPyRenderer.extractFqn(ref.name());
        if (availableFqns.contains(fqn)) {
            importByName.put(ApiTypeRefPyRenderer.simplePyName(fqn), fqn);
        }
    }

    /** {@code Class<?>} → {@link ApiTypeRef}（镜像 TypeReflector.classToRef 的映射，best-effort）。 */
    static ApiTypeRef classToTypeRef(Class<?> cls) {
        if (cls == void.class || cls == Void.class) return ApiTypeRef.voidType();
        if (cls == String.class || cls == char.class || cls == Character.class) return ApiTypeRef.primitive("string");
        if (cls == boolean.class || cls == Boolean.class) return ApiTypeRef.primitive("boolean");
        if (cls == float.class || cls == Float.class || cls == double.class || cls == Double.class) {
            return ApiTypeRef.primitive("float");
        }
        if (cls.isPrimitive() || Number.class.isAssignableFrom(cls)) return ApiTypeRef.primitive("int");
        if (cls == Object.class) return ApiTypeRef.primitive("object");
        if (cls.isArray()) return ApiTypeRef.array(classToTypeRef(cls.getComponentType()));
        return ApiTypeRef.symbol(new ApiSymbolId("java", cls.getName()));
    }

    private static String pkgOf(String fqn) {
        int dot = fqn.lastIndexOf('.');
        return dot >= 0 ? fqn.substring(0, dot) : "";
    }

    /** 单个事件的渲染信息：条目 + 已渲染的事件类型 / dispatch key 类型（null = 无 key 重载）。 */
    private record EventInfo(EventCatalogEntry entry, String eventType, String keyType) {}
}
