package com.tkisor.nekojs.probe.backend.python;

import com.tkisor.nekojs.api.catalog.RegistryBuilderSurfaceEntry;

import java.util.List;

/**
 * typed Builder 契约条目 → Python 声明（ticket 15，AC4/AC9）。
 * 输入是 {@link RegistryBuilderSurfaceEntry}——与 TS 侧
 * {@code RegistryBuilderTsRenderer} 同一条目列表，成员语义两侧一致。
 * 成员名保持 JS 面 verbatim（{@code maxStackSize}/{@code setMaxStackSize}）。
 * {@link PythonProbeBackend} 与 contract/golden 测试共用本渲染器。
 */
public final class RegistryBuilderPyRenderer {

    private RegistryBuilderPyRenderer() {}

    /** 渲染 {@code nekojs/_registry_builders/__init__.pyi} 内容；空列表返回空串。 */
    public static String render(List<RegistryBuilderSurfaceEntry> entries) {
        if (entries == null || entries.isEmpty()) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        sb.append("# Auto-generated by NekoJS probe. Derived from RegistryBuilderContract reflection over the builder classes (ticket 15).\n");
        sb.append("# Do not edit; regenerate with /nekojs probe.\n\n");
        sb.append("from typing import Any, Protocol\n\n");
        for (RegistryBuilderSurfaceEntry entry : entries) {
            sb.append("# ").append(entry.builderName())
                    .append(" — registry '").append(entry.registryKey()).append('\'')
                    .append(", type '").append(entry.typeName()).append('\'');
            if (entry.sugarName() != null && !entry.sugarName().isEmpty()) {
                sb.append(", sugar '").append(entry.sugarName()).append('\'');
            }
            sb.append("\nclass ").append(entry.builderName()).append("(Protocol):\n");
            for (RegistryBuilderSurfaceEntry.Member member : entry.members()) {
                switch (member.kind()) {
                    case WRITABLE_PROPERTY -> sb.append("    ").append(member.name()).append(": ")
                            .append(member.pyType()).append("\n");
                    case READ_ONLY_PROPERTY -> sb.append("    ").append(member.name()).append(": ")
                            .append(member.pyType()).append("  # read-only\n");
                    case METHOD -> sb.append("    ").append(member.pyType()).append("\n");
                }
            }
            sb.append("\n");
        }
        return sb.toString();
    }
}
