import { $AuthenticationService, $GameProfile, $GameProfileRepository, $HttpAuthenticationService, $ProfileLookupCallback, $SignatureState } from "java:com/mojang/authlib";
import { $BanDetails, $MinecraftProfileTexture, $MinecraftProfileTextures, $MinecraftSessionService, $TelemetryEvent, $TelemetryPropertyContainer, $TelemetrySession, $UserApiService, $UserApiService$UserFlag, $UserApiService$UserProperties } from "java:com/mojang/authlib/minecraft";
import { $AbuseReport, $AbuseReportLimits, $ReportChatMessage, $ReportEvidence, $ReportedEntity } from "java:com/mojang/authlib/minecraft/report";
import { $Property, $PropertyMap } from "java:com/mojang/authlib/properties";
import { $ProfileActionType, $ProfileResult, $ServicesKeyInfo, $ServicesKeySet, $ServicesKeyType, $YggdrasilAuthenticationService } from "java:com/mojang/authlib/yggdrasil";
import { $AbuseReportRequest, $AbuseReportRequest$ClientInfo, $AbuseReportRequest$RealmInfo, $AbuseReportRequest$ThirdPartyServerInfo } from "java:com/mojang/authlib/yggdrasil/request";
import { $KeyPairResponse, $KeyPairResponse$KeyPair } from "java:com/mojang/authlib/yggdrasil/response";
import { $ListenerTransform, $SoundBuffer } from "java:com/mojang/blaze3d/audio";
import { $RenderTarget } from "java:com/mojang/blaze3d/pipeline";
import { $IconSet, $InputConstants$Key, $InputConstants$Type, $Monitor, $NativeImage, $NativeImage$Format, $VideoMode, $Window, $WindowEventHandler } from "java:com/mojang/blaze3d/platform";
import { $GlslPreprocessor } from "java:com/mojang/blaze3d/preprocessor";
import { $AbstractUniform, $BlendMode, $Effect, $EffectProgram, $FogShape, $Program, $Program$Type, $Shader, $Uniform } from "java:com/mojang/blaze3d/shaders";
import { $BufferBuilder, $ByteBufferBuilder, $ByteBufferBuilder$Result, $MeshData, $MeshData$DrawState, $MeshData$SortState, $PoseStack, $PoseStack$Pose, $Tesselator, $VertexBuffer, $VertexConsumer, $VertexFormat, $VertexFormat$Builder, $VertexFormat$IndexType, $VertexFormat$Mode, $VertexFormatElement, $VertexFormatElement$Type, $VertexFormatElement$Usage, $VertexSorting, $VertexSorting$DistanceFunction } from "java:com/mojang/blaze3d/vertex";
import { $AmbiguityConsumer, $Command, $CommandDispatcher, $ImmutableStringReader, $Message, $ParseResults, $RedirectModifier, $ResultConsumer, $SingleRedirectModifier, $StringReader } from "java:com/mojang/brigadier";
import { $ArgumentType } from "java:com/mojang/brigadier/arguments";
import { $ArgumentBuilder, $LiteralArgumentBuilder, $RequiredArgumentBuilder } from "java:com/mojang/brigadier/builder";
import { $CommandContext, $CommandContextBuilder, $ContextChain, $ContextChain$Stage, $ParsedArgument, $ParsedCommandNode, $StringRange, $SuggestionContext } from "java:com/mojang/brigadier/context";
import { $BuiltInExceptionProvider, $CommandExceptionType, $CommandSyntaxException, $Dynamic2CommandExceptionType, $DynamicCommandExceptionType, $SimpleCommandExceptionType } from "java:com/mojang/brigadier/exceptions";
import { $Suggestion, $SuggestionProvider, $Suggestions, $SuggestionsBuilder } from "java:com/mojang/brigadier/suggestion";
import { $ArgumentCommandNode, $CommandNode, $LiteralCommandNode, $RootCommandNode } from "java:com/mojang/brigadier/tree";
import { $DSL$TypeReference, $DataFixer, $FamilyOptic, $OpticFinder, $Products$P1, $Products$P10, $Products$P11, $Products$P12, $Products$P13, $Products$P14, $Products$P15, $Products$P16, $Products$P2, $Products$P3, $Products$P4, $Products$P5, $Products$P6, $Products$P7, $Products$P8, $Products$P9, $RewriteResult, $TypeRewriteRule, $Typed, $TypedOptic, $View } from "java:com/mojang/datafixers";
import { $PointFree, $PointFreeRule } from "java:com/mojang/datafixers/functions";
import { $App, $App2, $Applicative, $Functor, $K1, $Kind1 } from "java:com/mojang/datafixers/kinds";
import { $Optic } from "java:com/mojang/datafixers/optics";
import { $Schema } from "java:com/mojang/datafixers/schemas";
import { $Type, $Type$FieldNotFoundException, $Type$Mu, $Type$TypeError, $Type$TypeMatcher } from "java:com/mojang/datafixers/types";
import { $Algebra, $RecursiveTypeFamily, $TypeFamily } from "java:com/mojang/datafixers/types/families";
import { $RecursivePoint$RecursivePointType, $TaggedChoice$TaggedChoiceType, $TypeTemplate } from "java:com/mojang/datafixers/types/templates";
import { $Either, $Either$Mu, $Function10, $Function11, $Function12, $Function13, $Function14, $Function15, $Function16, $Function3, $Function4, $Function5, $Function6, $Function7, $Function8, $Function9, $Pair, $Pair$Mu, $Unit } from "java:com/mojang/datafixers/util";
import { $OctahedralGroup, $Transformation } from "java:com/mojang/math";
import { $RealmsClient, $RealmsClient$CompatibleVersionResponse, $RealmsClient$Environment } from "java:com/mojang/realmsclient/client";
import { $Backup, $BackupList, $Ops, $PendingInvite, $PendingInvitesList, $PingResult, $PlayerInfo, $RealmsNews, $RealmsNotification, $RealmsServer, $RealmsServer$Compatibility, $RealmsServer$State, $RealmsServer$WorldType, $RealmsServerAddress, $RealmsServerList, $RealmsServerPlayerLists, $RealmsWorldOptions, $ReflectionBasedSerialization, $RegionPingResult, $ServerActivity, $ServerActivityList, $Subscription, $Subscription$SubscriptionType, $UploadInfo, $ValueObject, $WorldDownload, $WorldTemplate, $WorldTemplate$WorldTemplateType, $WorldTemplatePaginatedList } from "java:com/mojang/realmsclient/dto";
import { $RealmsDataFetcher, $RealmsDataFetcher$ServerListData, $RealmsNewsManager } from "java:com/mojang/realmsclient/gui";
import { $DataFetcher, $DataFetcher$Subscription, $DataFetcher$Task, $RepeatedDelayStrategy } from "java:com/mojang/realmsclient/gui/task";
import { $LevelType, $WorldGenerationInfo } from "java:com/mojang/realmsclient/util";
import { $Codec, $Codec$ResultFunction, $Compressable, $CompressorHolder, $DataResult, $DataResult$Error, $DataResult$Instance, $DataResult$Mu, $Decoder, $Decoder$Boxed, $Decoder$Simple, $Decoder$Terminal, $Dynamic, $DynamicLike, $DynamicOps, $Encoder, $KeyCompressor, $Keyable, $Lifecycle, $ListBuilder, $MapCodec, $MapCodec$ResultFunction, $MapDecoder, $MapEncoder, $MapLike, $OptionalDynamic, $RecordBuilder } from "java:com/mojang/serialization";
import { $BaseMapCodec, $PrimitiveCodec, $RecordCodecBuilder, $RecordCodecBuilder$Instance, $RecordCodecBuilder$Mu, $SimpleMapCodec, $UnboundedMapCodec } from "java:com/mojang/serialization/codecs";
import { $RecipeBuilder, $RecipeCreationContext, $RecipeEntryJS, $RecipeFilter, $RecipeJsonBuilder, $RecipeJsonValue, $RecipeLifecycleContext } from "java:com/tkisor/nekojs/api/recipe";
import { $RecipeFieldDefinition, $RecipeFieldKind, $RecipeFieldRole, $RecipeTypeDefinition, $RecipeTypeDefinitionRegistry, $RecipeTypeDefinitionRegistry$Builder } from "java:com/tkisor/nekojs/api/recipe/definition";
import { $PostEffectEventJS } from "java:com/tkisor/nekojs/client/posteffect";
import { $BlockEntityTickEvent, $RandomTickEvent } from "java:com/tkisor/nekojs/event/level";
import { $DataGeneratorJS, $LangGeneratorJS, $RecipeRegistryProxy } from "java:com/tkisor/nekojs/wrapper";
import { $PainterJS, $ScreenRenderEventJS } from "java:com/tkisor/nekojs/wrapper/client";
import { $GoalRegistry$GoalBuilderJS } from "java:com/tkisor/nekojs/wrapper/entity";
import { $BlockBrokenEventJS } from "java:com/tkisor/nekojs/wrapper/event/block";
import { $GoalRegisterEventJS } from "java:com/tkisor/nekojs/wrapper/event/entity";
import { $InventoryChangedEventJS } from "java:com/tkisor/nekojs/wrapper/event/player";
import { $CapabilityRegistryEventJS } from "java:com/tkisor/nekojs/wrapper/event/registry";
import { $ItemModificationEventJS, $ItemModificationJS, $LootEntryJS, $LootPoolJS, $LootTableEventJS, $LootTableJS, $RecipeEventJS, $TagEventJS } from "java:com/tkisor/nekojs/wrapper/event/server";
import { $RecipeViewerCategoryListJS, $RecipeViewerEntryListJS, $RecipeViewerInformationJS, $RecipeViewerRecipeListJS } from "java:com/tkisor/nekojs/wrapper/viewer";
import { $BufferedReader, $Closeable, $DataInput, $DataOutput, $File, $FileFilter, $FilenameFilter, $FilterOutputStream, $Flushable, $InputStream, $OutputStream, $PrintStream, $PrintWriter, $Reader, $Serializable, $Writer } from "java:java/io";
import { $AbstractStringBuilder, $Appendable, $AutoCloseable, $Boolean, $Byte, $CharSequence, $Character, $Class, $ClassLoader, $Cloneable, $Comparable, $Double, $Enum, $Enum$EnumDesc, $Exception, $Float, $IllegalStateException, $Integer, $Iterable, $Long, $Module, $ModuleLayer, $ModuleLayer$Controller, $NamedPackage, $Number, $Package, $Readable, $Record, $Runnable, $Runtime$Version, $RuntimeException, $Short, $StackTraceElement, $String, $StringBuffer, $StringBuilder, $Thread, $Thread$Builder, $Thread$Builder$OfPlatform, $Thread$Builder$OfVirtual, $Thread$State, $Thread$UncaughtExceptionHandler, $ThreadGroup, $Throwable, $Void } from "java:java/lang";
import { $Annotation } from "java:java/lang/annotation";
import { $ClassDesc, $Constable, $ConstantDesc, $DirectMethodHandleDesc, $DirectMethodHandleDesc$Kind, $DynamicConstantDesc, $MethodHandleDesc, $MethodTypeDesc } from "java:java/lang/constant";
import { $AddressLayout, $Arena, $GroupLayout, $MemoryLayout, $MemoryLayout$PathElement, $MemorySegment, $MemorySegment$Scope, $PaddingLayout, $SegmentAllocator, $SequenceLayout, $StructLayout, $UnionLayout, $ValueLayout, $ValueLayout$OfBoolean, $ValueLayout$OfByte, $ValueLayout$OfChar, $ValueLayout$OfDouble, $ValueLayout$OfFloat, $ValueLayout$OfInt, $ValueLayout$OfLong, $ValueLayout$OfShort } from "java:java/lang/foreign";
import { $MethodHandle, $MethodHandleInfo, $MethodHandles$Lookup, $MethodHandles$Lookup$ClassOption, $MethodType, $TypeDescriptor, $TypeDescriptor$OfField, $TypeDescriptor$OfMethod, $VarHandle, $VarHandle$AccessMode, $VarHandle$VarHandleDesc } from "java:java/lang/invoke";
import { $Configuration, $ModuleDescriptor, $ModuleDescriptor$Builder, $ModuleDescriptor$Exports, $ModuleDescriptor$Exports$Modifier, $ModuleDescriptor$Modifier, $ModuleDescriptor$Opens, $ModuleDescriptor$Opens$Modifier, $ModuleDescriptor$Provides, $ModuleDescriptor$Requires, $ModuleDescriptor$Requires$Modifier, $ModuleDescriptor$Version, $ModuleFinder, $ModuleReader, $ModuleReference, $ResolvedModule } from "java:java/lang/module";
import { $AccessFlag, $AccessFlag$Location, $AccessibleObject, $AnnotatedElement, $AnnotatedType, $ClassFileFormatVersion, $Constructor, $Executable, $Field, $GenericDeclaration, $Member, $Method, $Parameter, $RecordComponent, $Type, $TypeVariable } from "java:java/lang/reflect";
import { $RoundingMode } from "java:java/math";
import { $ContentHandler, $ContentHandlerFactory, $FileNameMap, $InetAddress, $InetSocketAddress, $InterfaceAddress, $NetworkInterface, $Proxy, $Proxy$Type, $SocketAddress, $URI, $URL, $URLConnection, $URLStreamHandler, $URLStreamHandlerFactory } from "java:java/net";
import { $Buffer, $ByteBuffer, $ByteOrder, $CharBuffer, $DoubleBuffer, $FloatBuffer, $IntBuffer, $LongBuffer, $MappedByteBuffer, $ShortBuffer } from "java:java/nio";
import { $AsynchronousChannel, $AsynchronousFileChannel, $ByteChannel, $Channel, $CompletionHandler, $FileChannel, $FileChannel$MapMode, $FileLock, $GatheringByteChannel, $InterruptibleChannel, $ReadableByteChannel, $ScatteringByteChannel, $SeekableByteChannel, $WritableByteChannel } from "java:java/nio/channels";
import { $AbstractInterruptibleChannel } from "java:java/nio/channels/spi";
import { $Charset, $CharsetDecoder, $CharsetEncoder, $CoderResult, $CodingErrorAction } from "java:java/nio/charset";
import { $AccessMode, $CopyOption, $DirectoryStream, $DirectoryStream$Filter, $FileStore, $FileSystem, $LinkOption, $OpenOption, $Path, $PathMatcher, $WatchEvent, $WatchEvent$Kind, $WatchEvent$Modifier, $WatchKey, $WatchService, $Watchable } from "java:java/nio/file";
import { $FileAttribute, $FileTime, $GroupPrincipal, $UserPrincipal, $UserPrincipalLookupService } from "java:java/nio/file/attribute";
import { $FileSystemProvider } from "java:java/nio/file/spi";
import { $AlgorithmParameters, $CodeSigner, $CodeSource, $Guard, $Key, $KeyPair, $Permission, $PermissionCollection, $Principal, $PrivateKey, $ProtectionDomain, $Provider, $Provider$Service, $PublicKey, $SecureRandom, $SecureRandomParameters, $Signature, $SignatureSpi, $Timestamp } from "java:java/security";
import { $CertPath, $Certificate } from "java:java/security/cert";
import { $AlgorithmParameterSpec } from "java:java/security/spec";
import { $AttributedCharacterIterator, $AttributedCharacterIterator$Attribute, $CharacterIterator, $DateFormat, $DateFormatSymbols, $DecimalFormat, $DecimalFormatSymbols, $FieldPosition, $Format, $Format$Field, $NumberFormat, $NumberFormat$Style, $ParsePosition, $SimpleDateFormat } from "java:java/text";
import { $Clock, $DayOfWeek, $Duration, $Instant, $InstantSource, $LocalDate, $LocalDateTime, $LocalTime, $Month, $OffsetDateTime, $OffsetTime, $Period, $ZoneId, $ZoneOffset, $ZonedDateTime } from "java:java/time";
import { $AbstractChronology, $ChronoLocalDate, $ChronoLocalDateTime, $ChronoPeriod, $ChronoZonedDateTime, $Chronology, $Era, $IsoChronology, $IsoEra } from "java:java/time/chrono";
import { $DateTimeFormatter, $DecimalStyle, $FormatStyle, $ResolverStyle, $TextStyle } from "java:java/time/format";
import { $ChronoField, $ChronoUnit, $Temporal, $TemporalAccessor, $TemporalAdjuster, $TemporalAmount, $TemporalField, $TemporalQuery, $TemporalUnit, $ValueRange } from "java:java/time/temporal";
import { $ZoneOffsetTransition, $ZoneOffsetTransitionRule, $ZoneOffsetTransitionRule$TimeDefinition, $ZoneRules } from "java:java/time/zone";
import { $AbstractCollection, $AbstractList, $AbstractSet, $ArrayList, $BitSet, $Calendar, $Collection, $Comparator, $Currency, $Date, $Deque, $Dictionary, $DoubleSummaryStatistics, $EnumSet, $Enumeration, $Hashtable, $IntSummaryStatistics, $Iterator, $List, $ListIterator, $Locale, $Locale$Category, $Locale$FilteringMode, $Locale$IsoCountryCode, $Locale$LanguageRange, $LongSummaryStatistics, $Map, $Map$Entry, $Optional, $OptionalDouble, $OptionalInt, $OptionalLong, $PrimitiveIterator, $PrimitiveIterator$OfDouble, $PrimitiveIterator$OfInt, $PrimitiveIterator$OfLong, $Properties, $Queue, $Random, $RandomAccess, $SequencedCollection, $SequencedMap, $SequencedSet, $Set, $SortedMap, $Spliterator, $Spliterator$OfDouble, $Spliterator$OfInt, $Spliterator$OfLong, $Spliterator$OfPrimitive, $TimeZone, $UUID } from "java:java/util";
import { $Callable, $CompletableFuture, $CompletionStage, $Executor, $ExecutorService, $Future, $Future$State, $ThreadFactory, $TimeUnit } from "java:java/util/concurrent";
import { $AtomicReference } from "java:java/util/concurrent/atomic";
import { $BiConsumer, $BiFunction, $BiPredicate, $BinaryOperator, $BooleanSupplier, $Consumer, $DoubleBinaryOperator, $DoubleConsumer, $DoubleFunction, $DoublePredicate, $DoubleSupplier, $DoubleToIntFunction, $DoubleToLongFunction, $DoubleUnaryOperator, $Function, $IntBinaryOperator, $IntConsumer, $IntFunction, $IntPredicate, $IntSupplier, $IntToDoubleFunction, $IntToLongFunction, $IntUnaryOperator, $LongBinaryOperator, $LongConsumer, $LongFunction, $LongPredicate, $LongSupplier, $LongToDoubleFunction, $LongToIntFunction, $LongUnaryOperator, $ObjDoubleConsumer, $ObjIntConsumer, $ObjLongConsumer, $Predicate, $Supplier, $ToDoubleFunction, $ToIntFunction, $ToLongFunction, $UnaryOperator } from "java:java/util/function";
import { $RandomGenerator } from "java:java/util/random";
import { $BaseStream, $Collector, $Collector$Characteristics, $DoubleStream, $DoubleStream$Builder, $DoubleStream$DoubleMapMultiConsumer, $IntStream, $IntStream$Builder, $IntStream$IntMapMultiConsumer, $LongStream, $LongStream$Builder, $LongStream$LongMapMultiConsumer, $Stream, $Stream$Builder } from "java:java/util/stream";
import { $ZipConstants, $ZipEntry, $ZipFile } from "java:java/util/zip";
import { $BlockUtil$FoundRectangle, $ChatFormatting, $CrashReport, $CrashReportCategory, $CrashReportDetail, $ReportType, $ReportedException, $SystemReport } from "java:net/minecraft";
import { $Advancement, $AdvancementHolder, $AdvancementNode, $AdvancementProgress, $AdvancementRequirements, $AdvancementRewards, $AdvancementTree, $AdvancementTree$Listener, $AdvancementType, $Criterion, $CriterionProgress, $CriterionTrigger, $CriterionTrigger$Listener, $DisplayInfo } from "java:net/minecraft/advancements";
import { $AttackIndicatorStatus, $Camera, $Camera$NearPlane, $CameraType, $ClientRecipeBook, $CloudStatus, $CommandHistory, $DebugQueryHandler, $DeltaTracker, $GameNarrator, $GraphicsStatus, $GuiMessageTag, $GuiMessageTag$Icon, $HotbarManager, $InputType, $KeyMapping, $KeyboardHandler, $Minecraft, $Minecraft$ChatStatus, $Minecraft$GameLoadCookie, $MouseHandler, $NarratorStatus, $OptionInstance, $OptionInstance$CaptionBasedToString, $OptionInstance$CycleableValueSet, $OptionInstance$CycleableValueSet$ValueSetter, $OptionInstance$Enum, $OptionInstance$TooltipSupplier, $OptionInstance$ValueSet, $Options, $ParticleStatus, $PrioritizeChunkUpdates, $RecipeBookCategories, $StringSplitter, $StringSplitter$LinePosConsumer, $User, $User$Type } from "java:net/minecraft/client";
import { $BlockColor, $BlockColors } from "java:net/minecraft/client/color/block";
import { $ItemColor, $ItemColors } from "java:net/minecraft/client/color/item";
import { $ComponentPath, $Font, $Font$DisplayMode, $Gui, $GuiGraphics, $GuiSpriteManager, $MapRenderer } from "java:net/minecraft/client/gui";
import { $AbstractWidget, $BossHealthOverlay, $ChatComponent, $ChatComponent$State, $CycleButton$ValueListSupplier, $DebugScreenOverlay, $PlayerTabOverlay, $Renderable, $SplashRenderer, $TabOrderedElement, $Tooltip } from "java:net/minecraft/client/gui/components";
import { $AbstractContainerEventHandler, $ContainerEventHandler, $GuiEventListener } from "java:net/minecraft/client/gui/components/events";
import { $SpectatorGui } from "java:net/minecraft/client/gui/components/spectator";
import { $Toast, $Toast$Visibility, $ToastComponent, $TutorialToast } from "java:net/minecraft/client/gui/components/toasts";
import { $LayoutElement } from "java:net/minecraft/client/gui/layouts";
import { $NarratableEntry, $NarratableEntry$NarrationPriority, $NarratedElementType, $NarrationElementOutput, $NarrationSupplier, $NarrationThunk } from "java:net/minecraft/client/gui/narration";
import { $FocusNavigationEvent, $ScreenAxis, $ScreenDirection, $ScreenPosition, $ScreenRectangle } from "java:net/minecraft/client/gui/navigation";
import { $MenuScreens$ScreenConstructor, $Overlay, $ReceivingLevelScreen$Reason, $Screen, $Screen$NarratableSearchResult } from "java:net/minecraft/client/gui/screens";
import { $AbstractContainerScreen, $EffectRenderingInventoryScreen, $MenuAccess } from "java:net/minecraft/client/gui/screens/inventory";
import { $ClientTooltipPositioner } from "java:net/minecraft/client/gui/screens/inventory/tooltip";
import { $RecipeCollection } from "java:net/minecraft/client/gui/screens/recipebook";
import { $PlayerSocialManager } from "java:net/minecraft/client/gui/screens/social";
import { $CreateWorldScreen, $PresetEditor, $WorldCreationContext, $WorldCreationContext$DimensionsUpdater, $WorldCreationContext$OptionsModifier, $WorldCreationUiState, $WorldCreationUiState$SelectedGameMode, $WorldCreationUiState$WorldTypeEntry, $WorldOpenFlows } from "java:net/minecraft/client/gui/screens/worldselection";
import { $SpectatorMenu, $SpectatorMenuCategory, $SpectatorMenuItem, $SpectatorMenuListener } from "java:net/minecraft/client/gui/spectator";
import { $SpectatorPage } from "java:net/minecraft/client/gui/spectator/categories";
import { $GameConfig$QuickPlayData } from "java:net/minecraft/client/main";
import { $AgeableListModel, $ArmedModel, $EntityModel, $HeadedModel, $HumanoidModel, $HumanoidModel$ArmPose, $Model } from "java:net/minecraft/client/model";
import { $EntityModelSet, $ModelLayerLocation, $ModelPart, $ModelPart$Cube, $ModelPart$Visitor, $PartPose } from "java:net/minecraft/client/model/geom";
import { $CubeDefinition, $CubeDeformation, $CubeListBuilder, $MeshDefinition, $PartDefinition } from "java:net/minecraft/client/model/geom/builders";
import { $ClientAdvancements, $ClientAdvancements$Listener, $ClientChunkCache, $ClientCommonPacketListenerImpl, $ClientLevel, $ClientLevel$ClientLevelData, $ClientPacketListener, $ClientSuggestionProvider, $MultiPlayerGameMode, $PlayerInfo, $ProfileKeyPairManager, $ServerData, $ServerData$ServerPackStatus, $ServerData$State, $ServerData$Type, $SessionSearchTrees, $SessionSearchTrees$Key } from "java:net/minecraft/client/multiplayer";
import { $ChatListener, $ChatLog, $LoggedChatEvent, $LoggedChatEvent$Type } from "java:net/minecraft/client/multiplayer/chat";
import { $AbuseReportSender, $Report, $ReportEnvironment, $ReportEnvironment$Server, $ReportType, $ReportingContext } from "java:net/minecraft/client/multiplayer/chat/report";
import { $Particle, $ParticleEngine, $ParticleEngine$SpriteParticleRegistration, $ParticleProvider, $ParticleProvider$Sprite, $ParticleRenderType, $SingleQuadParticle, $SingleQuadParticle$FacingCameraMode, $SpriteSet, $TextureSheetParticle } from "java:net/minecraft/client/particle";
import { $AbstractClientPlayer, $Input, $LocalPlayer } from "java:net/minecraft/client/player";
import { $Hotbar } from "java:net/minecraft/client/player/inventory";
import { $QuickPlayLog, $QuickPlayLog$Type } from "java:net/minecraft/client/quickplay";
import { $BlockEntityWithoutLevelRenderer, $DimensionSpecialEffects, $DimensionSpecialEffects$SkyType, $EffectInstance, $FogRenderer$FogMode, $GameRenderer, $GpuWarnlistManager, $ItemInHandRenderer, $ItemModelShaper, $LevelRenderer, $LightTexture, $MultiBufferSource, $MultiBufferSource$BufferSource, $OutlineBufferSource, $PostChain, $PostPass, $RenderBuffers, $RenderStateShard, $RenderStateShard$BooleanStateShard, $RenderStateShard$ColorLogicStateShard, $RenderStateShard$CullStateShard, $RenderStateShard$DepthTestStateShard, $RenderStateShard$EmptyTextureStateShard, $RenderStateShard$LayeringStateShard, $RenderStateShard$LightmapStateShard, $RenderStateShard$LineStateShard, $RenderStateShard$OutputStateShard, $RenderStateShard$OverlayStateShard, $RenderStateShard$ShaderStateShard, $RenderStateShard$TextureStateShard, $RenderStateShard$TexturingStateShard, $RenderStateShard$TransparencyStateShard, $RenderStateShard$WriteMaskStateShard, $RenderType, $RenderType$CompositeRenderType, $RenderType$CompositeState, $RenderType$CompositeState$CompositeStateBuilder, $RenderType$OutlineProperty, $SectionBufferBuilderPack, $SectionBufferBuilderPool, $ShaderInstance } from "java:net/minecraft/client/renderer";
import { $BlockModelShaper, $BlockRenderDispatcher, $LiquidBlockRenderer, $ModelBlockRenderer } from "java:net/minecraft/client/renderer/block";
import { $BakedQuad, $BlockElement, $BlockElementFace, $BlockElementRotation, $BlockFaceUV, $BlockModel, $BlockModel$GuiLight, $ItemOverride, $ItemOverride$Predicate, $ItemOverrides, $ItemOverrides$BakedOverride, $ItemTransform, $ItemTransforms } from "java:net/minecraft/client/renderer/block/model";
import { $BlockEntityRenderDispatcher, $BlockEntityRenderer, $BlockEntityRendererProvider, $BlockEntityRendererProvider$Context } from "java:net/minecraft/client/renderer/blockentity";
import { $RenderChunkRegion, $RenderRegionCache, $SectionRenderDispatcher, $SectionRenderDispatcher$CompiledSection, $SectionRenderDispatcher$RenderSection, $SectionRenderDispatcher$RenderSection$CompileTask, $SectionRenderDispatcher$SectionTaskResult } from "java:net/minecraft/client/renderer/chunk";
import { $Frustum } from "java:net/minecraft/client/renderer/culling";
import { $BeeDebugRenderer, $BrainDebugRenderer, $BrainDebugRenderer$PoiInfo, $BreezeDebugRenderer, $DebugRenderer, $DebugRenderer$SimpleDebugRenderer, $GameEventListenerRenderer, $GameTestDebugRenderer, $GoalSelectorDebugRenderer, $LightSectionDebugRenderer, $PathfindingRenderer, $RaidDebugRenderer, $StructureRenderer, $VillageSectionsDebugRenderer } from "java:net/minecraft/client/renderer/debug";
import { $EntityRenderDispatcher, $EntityRenderer, $EntityRendererProvider, $EntityRendererProvider$Context, $ItemRenderer } from "java:net/minecraft/client/renderer/entity";
import { $AbstractTexture, $Dumpable, $DynamicTexture, $OverlayTexture, $SpriteContents, $SpriteLoader$Preparations, $SpriteTicker, $Stitcher$Entry, $TextureAtlas, $TextureAtlasSprite, $TextureAtlasSprite$Ticker, $TextureManager, $Tickable } from "java:net/minecraft/client/renderer/texture";
import { $MapDecorationTextureManager, $MobEffectTextureManager, $PaintingTextureManager, $PlayerSkin, $PlayerSkin$Model, $SkinManager, $SplashManager, $TextureAtlasHolder } from "java:net/minecraft/client/resources";
import { $LanguageInfo, $LanguageManager } from "java:net/minecraft/client/resources/language";
import { $GuiSpriteScaling, $GuiSpriteScaling$Type } from "java:net/minecraft/client/resources/metadata/gui";
import { $BakedModel, $Material, $ModelBaker, $ModelBakery, $ModelBakery$TextureGetter, $ModelManager, $ModelResourceLocation, $ModelState, $UnbakedModel } from "java:net/minecraft/client/resources/model";
import { $DownloadedPackSource, $ServerPackManager$PackPromptStatus } from "java:net/minecraft/client/resources/server";
import { $Sound, $Sound$Type, $SoundInstance, $SoundInstance$Attenuation, $TickableSoundInstance } from "java:net/minecraft/client/resources/sounds";
import { $SearchTree } from "java:net/minecraft/client/searchtree";
import { $IntegratedServer } from "java:net/minecraft/client/server";
import { $AudioStream, $MusicManager, $SoundBufferLibrary, $SoundEngine, $SoundEventListener, $SoundManager, $WeighedSoundEvents, $Weighted } from "java:net/minecraft/client/sounds";
import { $ClientTelemetryManager, $TelemetryEventInstance, $TelemetryEventSender, $TelemetryEventType, $TelemetryEventType$Builder, $TelemetryProperty, $TelemetryProperty$Exporter, $TelemetryProperty$GameMode, $TelemetryProperty$ServerType, $TelemetryPropertyMap, $TelemetryPropertyMap$Builder, $WorldSessionTelemetryManager } from "java:net/minecraft/client/telemetry";
import { $GameLoadTimesEvent$Measurement } from "java:net/minecraft/client/telemetry/events";
import { $Tutorial, $TutorialStepInstance, $TutorialSteps } from "java:net/minecraft/client/tutorial";
import { $CacheableFunction, $CommandBuildContext, $CommandResultCallback, $CommandSigningContext, $CommandSource, $CommandSourceStack, $Commands, $Commands$CommandSelection, $Commands$ParseFunction, $ExecutionCommandSource, $SharedSuggestionProvider, $SharedSuggestionProvider$ElementSuggestionType, $SharedSuggestionProvider$TextCoordinates } from "java:net/minecraft/commands";
import { $ArgumentSignatures, $ArgumentSignatures$Entry, $ArgumentSignatures$Signer, $EntityAnchorArgument$Anchor } from "java:net/minecraft/commands/arguments";
import { $CommandQueueEntry, $EntryAction, $ExecutionContext, $Frame, $Frame$FrameControl, $TraceCallbacks, $UnboundEntryAction } from "java:net/minecraft/commands/execution";
import { $CommandFunction, $InstantiatedFunction } from "java:net/minecraft/commands/functions";
import { $AxisCycle, $BlockPos, $BlockPos$MutableBlockPos, $Direction, $Direction$Axis, $Direction$AxisDirection, $Direction$Plane, $Direction8, $FrontAndTop, $GlobalPos, $Holder, $Holder$Kind, $Holder$Reference, $HolderGetter, $HolderGetter$Provider, $HolderLookup, $HolderLookup$Provider, $HolderLookup$RegistryLookup, $HolderOwner, $HolderSet, $HolderSet$Direct, $HolderSet$ListBacked, $HolderSet$Named, $IdMap, $IdMapper, $LayeredRegistryAccess, $NonNullList, $Position, $RegistrationInfo, $Registry, $RegistryAccess, $RegistryAccess$Frozen, $RegistryAccess$RegistryEntry, $Rotations, $SectionPos, $Vec3i } from "java:net/minecraft/core";
import { $DataComponentHolder, $DataComponentMap, $DataComponentMap$Builder, $DataComponentPatch, $DataComponentPatch$Builder, $DataComponentPatch$SplitResult, $DataComponentPredicate, $DataComponentPredicate$Builder, $DataComponentType, $DataComponentType$Builder, $PatchedDataComponentMap, $TypedDataComponent } from "java:net/minecraft/core/component";
import { $ParticleGroup, $ParticleOptions, $ParticleType, $SimpleParticleType } from "java:net/minecraft/core/particles";
import { $BootstrapContext } from "java:net/minecraft/data/worldgen";
import { $ByteArrayTag, $ByteTag, $CollectionTag, $CompoundTag, $DoubleTag, $EndTag, $FloatTag, $IntArrayTag, $IntTag, $ListTag, $LongArrayTag, $LongTag, $NbtAccounter, $NumericTag, $ShortTag, $StreamTagVisitor, $StreamTagVisitor$EntryResult, $StreamTagVisitor$ValueResult, $StringTag, $Tag, $TagType, $TagVisitor } from "java:net/minecraft/nbt";
import { $BandwidthDebugMonitor, $ClientboundPacketListener, $Connection, $ConnectionProtocol, $DisconnectionDetails, $FriendlyByteBuf, $PacketListener, $PacketSendListener, $ProtocolInfo, $RegistryFriendlyByteBuf, $ServerboundPacketListener, $TickablePacketListener } from "java:net/minecraft/network";
import { $ChatDecorator, $ChatType, $ChatType$Bound, $ChatTypeDecoration, $ChatTypeDecoration$Parameter, $ClickEvent, $ClickEvent$Action, $Component, $ComponentContents, $ComponentContents$Type, $FilterMask, $FormattedText, $FormattedText$ContentConsumer, $FormattedText$StyledContentConsumer, $HoverEvent, $HoverEvent$Action, $HoverEvent$EntityTooltipInfo, $HoverEvent$ItemStackInfo, $LastSeenMessages, $LastSeenMessages$Packed, $LastSeenMessages$Update, $MessageSignature, $MessageSignature$Packed, $MessageSignatureCache, $MutableComponent, $OutgoingChatMessage, $PlayerChatMessage, $RemoteChatSession, $RemoteChatSession$Data, $SignableCommand, $SignableCommand$Argument, $SignedMessageBody, $SignedMessageBody$Packed, $SignedMessageChain$Decoder, $SignedMessageLink, $SignedMessageValidator, $Style, $TextColor } from "java:net/minecraft/network/chat";
import { $DataSource, $DataSource$Type } from "java:net/minecraft/network/chat/contents";
import { $NumberFormat, $NumberFormatType } from "java:net/minecraft/network/chat/numbers";
import { $StreamCodec, $StreamCodec$CodecOperation, $StreamDecoder, $StreamEncoder, $StreamMemberEncoder } from "java:net/minecraft/network/codec";
import { $BundleDelimiterPacket, $BundlePacket, $BundlerInfo, $BundlerInfo$Bundler, $Packet, $PacketFlow, $PacketType } from "java:net/minecraft/network/protocol";
import { $ClientCommonPacketListener, $ClientboundCustomPayloadPacket, $ClientboundCustomReportDetailsPacket, $ClientboundDisconnectPacket, $ClientboundKeepAlivePacket, $ClientboundPingPacket, $ClientboundResourcePackPopPacket, $ClientboundResourcePackPushPacket, $ClientboundServerLinksPacket, $ClientboundStoreCookiePacket, $ClientboundTransferPacket, $ClientboundUpdateTagsPacket, $ServerCommonPacketListener, $ServerboundClientInformationPacket, $ServerboundCustomPayloadPacket, $ServerboundKeepAlivePacket, $ServerboundPongPacket, $ServerboundResourcePackPacket, $ServerboundResourcePackPacket$Action } from "java:net/minecraft/network/protocol/common";
import { $BeeDebugPayload$BeeInfo, $BrainDebugPayload$BrainDump, $BreezeDebugPayload$BreezeInfo, $CustomPacketPayload, $CustomPacketPayload$FallbackProvider, $CustomPacketPayload$Type, $CustomPacketPayload$TypeAndCodec, $GoalDebugPayload$DebugGoal, $HiveDebugPayload$HiveInfo, $StructuresDebugPayload$PieceInfo } from "java:net/minecraft/network/protocol/common/custom";
import { $ClientCookiePacketListener, $ClientboundCookieRequestPacket, $ServerCookiePacketListener, $ServerboundCookieResponsePacket } from "java:net/minecraft/network/protocol/cookie";
import { $ClientGamePacketListener, $ClientboundAddEntityPacket, $ClientboundAddExperienceOrbPacket, $ClientboundAnimatePacket, $ClientboundAwardStatsPacket, $ClientboundBlockChangedAckPacket, $ClientboundBlockDestructionPacket, $ClientboundBlockEntityDataPacket, $ClientboundBlockEventPacket, $ClientboundBlockUpdatePacket, $ClientboundBossEventPacket, $ClientboundBossEventPacket$Handler, $ClientboundBundlePacket, $ClientboundChangeDifficultyPacket, $ClientboundChunkBatchFinishedPacket, $ClientboundChunkBatchStartPacket, $ClientboundChunksBiomesPacket, $ClientboundChunksBiomesPacket$ChunkBiomeData, $ClientboundClearTitlesPacket, $ClientboundCommandSuggestionsPacket, $ClientboundCommandSuggestionsPacket$Entry, $ClientboundCommandsPacket, $ClientboundContainerClosePacket, $ClientboundContainerSetContentPacket, $ClientboundContainerSetDataPacket, $ClientboundContainerSetSlotPacket, $ClientboundCooldownPacket, $ClientboundCustomChatCompletionsPacket, $ClientboundCustomChatCompletionsPacket$Action, $ClientboundDamageEventPacket, $ClientboundDebugSamplePacket, $ClientboundDeleteChatPacket, $ClientboundDisguisedChatPacket, $ClientboundEntityEventPacket, $ClientboundExplodePacket, $ClientboundForgetLevelChunkPacket, $ClientboundGameEventPacket, $ClientboundGameEventPacket$Type, $ClientboundHorseScreenOpenPacket, $ClientboundHurtAnimationPacket, $ClientboundInitializeBorderPacket, $ClientboundLevelChunkPacketData, $ClientboundLevelChunkPacketData$BlockEntityTagOutput, $ClientboundLevelChunkWithLightPacket, $ClientboundLevelEventPacket, $ClientboundLevelParticlesPacket, $ClientboundLightUpdatePacket, $ClientboundLightUpdatePacketData, $ClientboundLoginPacket, $ClientboundMapItemDataPacket, $ClientboundMerchantOffersPacket, $ClientboundMoveEntityPacket, $ClientboundMoveVehiclePacket, $ClientboundOpenBookPacket, $ClientboundOpenScreenPacket, $ClientboundOpenSignEditorPacket, $ClientboundPlaceGhostRecipePacket, $ClientboundPlayerAbilitiesPacket, $ClientboundPlayerChatPacket, $ClientboundPlayerCombatEndPacket, $ClientboundPlayerCombatEnterPacket, $ClientboundPlayerCombatKillPacket, $ClientboundPlayerInfoRemovePacket, $ClientboundPlayerInfoUpdatePacket, $ClientboundPlayerInfoUpdatePacket$Action, $ClientboundPlayerInfoUpdatePacket$Entry, $ClientboundPlayerLookAtPacket, $ClientboundPlayerPositionPacket, $ClientboundProjectilePowerPacket, $ClientboundRecipePacket, $ClientboundRecipePacket$State, $ClientboundRemoveEntitiesPacket, $ClientboundRemoveMobEffectPacket, $ClientboundResetScorePacket, $ClientboundRespawnPacket, $ClientboundRotateHeadPacket, $ClientboundSectionBlocksUpdatePacket, $ClientboundSelectAdvancementsTabPacket, $ClientboundServerDataPacket, $ClientboundSetActionBarTextPacket, $ClientboundSetBorderCenterPacket, $ClientboundSetBorderLerpSizePacket, $ClientboundSetBorderSizePacket, $ClientboundSetBorderWarningDelayPacket, $ClientboundSetBorderWarningDistancePacket, $ClientboundSetCameraPacket, $ClientboundSetCarriedItemPacket, $ClientboundSetChunkCacheCenterPacket, $ClientboundSetChunkCacheRadiusPacket, $ClientboundSetDefaultSpawnPositionPacket, $ClientboundSetDisplayObjectivePacket, $ClientboundSetEntityDataPacket, $ClientboundSetEntityLinkPacket, $ClientboundSetEntityMotionPacket, $ClientboundSetEquipmentPacket, $ClientboundSetExperiencePacket, $ClientboundSetHealthPacket, $ClientboundSetObjectivePacket, $ClientboundSetPassengersPacket, $ClientboundSetPlayerTeamPacket, $ClientboundSetPlayerTeamPacket$Action, $ClientboundSetPlayerTeamPacket$Parameters, $ClientboundSetScorePacket, $ClientboundSetSimulationDistancePacket, $ClientboundSetSubtitleTextPacket, $ClientboundSetTimePacket, $ClientboundSetTitleTextPacket, $ClientboundSetTitlesAnimationPacket, $ClientboundSoundEntityPacket, $ClientboundSoundPacket, $ClientboundStartConfigurationPacket, $ClientboundStopSoundPacket, $ClientboundSystemChatPacket, $ClientboundTabListPacket, $ClientboundTagQueryPacket, $ClientboundTakeItemEntityPacket, $ClientboundTeleportEntityPacket, $ClientboundTickingStatePacket, $ClientboundTickingStepPacket, $ClientboundUpdateAdvancementsPacket, $ClientboundUpdateAttributesPacket, $ClientboundUpdateAttributesPacket$AttributeSnapshot, $ClientboundUpdateMobEffectPacket, $ClientboundUpdateRecipesPacket, $CommonPlayerSpawnInfo, $ServerGamePacketListener, $ServerPacketListener, $ServerboundAcceptTeleportationPacket, $ServerboundBlockEntityTagQueryPacket, $ServerboundChangeDifficultyPacket, $ServerboundChatAckPacket, $ServerboundChatCommandPacket, $ServerboundChatCommandSignedPacket, $ServerboundChatPacket, $ServerboundChatSessionUpdatePacket, $ServerboundChunkBatchReceivedPacket, $ServerboundClientCommandPacket, $ServerboundClientCommandPacket$Action, $ServerboundCommandSuggestionPacket, $ServerboundConfigurationAcknowledgedPacket, $ServerboundContainerButtonClickPacket, $ServerboundContainerClickPacket, $ServerboundContainerClosePacket, $ServerboundContainerSlotStateChangedPacket, $ServerboundDebugSampleSubscriptionPacket, $ServerboundEditBookPacket, $ServerboundEntityTagQueryPacket, $ServerboundInteractPacket, $ServerboundInteractPacket$Handler, $ServerboundJigsawGeneratePacket, $ServerboundLockDifficultyPacket, $ServerboundMovePlayerPacket, $ServerboundMoveVehiclePacket, $ServerboundPaddleBoatPacket, $ServerboundPickItemPacket, $ServerboundPlaceRecipePacket, $ServerboundPlayerAbilitiesPacket, $ServerboundPlayerActionPacket, $ServerboundPlayerActionPacket$Action, $ServerboundPlayerCommandPacket, $ServerboundPlayerCommandPacket$Action, $ServerboundPlayerInputPacket, $ServerboundRecipeBookChangeSettingsPacket, $ServerboundRecipeBookSeenRecipePacket, $ServerboundRenameItemPacket, $ServerboundSeenAdvancementsPacket, $ServerboundSeenAdvancementsPacket$Action, $ServerboundSelectTradePacket, $ServerboundSetBeaconPacket, $ServerboundSetCarriedItemPacket, $ServerboundSetCommandBlockPacket, $ServerboundSetCommandMinecartPacket, $ServerboundSetCreativeModeSlotPacket, $ServerboundSetJigsawBlockPacket, $ServerboundSetStructureBlockPacket, $ServerboundSignUpdatePacket, $ServerboundSwingPacket, $ServerboundTeleportToEntityPacket, $ServerboundUseItemOnPacket, $ServerboundUseItemPacket, $VecDeltaCodec } from "java:net/minecraft/network/protocol/game";
import { $ClientLoginPacketListener, $ClientboundCustomQueryPacket, $ClientboundGameProfilePacket, $ClientboundHelloPacket, $ClientboundLoginCompressionPacket, $ClientboundLoginDisconnectPacket } from "java:net/minecraft/network/protocol/login";
import { $CustomQueryPayload } from "java:net/minecraft/network/protocol/login/custom";
import { $ClientPongPacketListener, $ClientboundPongResponsePacket, $ServerPingPacketListener, $ServerboundPingRequestPacket } from "java:net/minecraft/network/protocol/ping";
import { $ClientStatusPacketListener, $ClientboundStatusResponsePacket, $ServerStatus, $ServerStatus$Favicon, $ServerStatus$Players, $ServerStatus$Version } from "java:net/minecraft/network/protocol/status";
import { $EntityDataAccessor, $EntityDataSerializer, $SyncedDataHolder, $SynchedEntityData, $SynchedEntityData$DataValue } from "java:net/minecraft/network/syncher";
import { $DelegatingOps, $FileToIdConverter, $RegistryOps, $RegistryOps$RegistryInfo, $RegistryOps$RegistryInfoLookup, $ResourceKey, $ResourceLocation } from "java:net/minecraft/resources";
import { $MinecraftServer, $MinecraftServer$ReloadableResources, $MinecraftServer$ServerResourcePackInfo, $PlayerAdvancements, $RegistryLayer, $ReloadableServerRegistries$Holder, $ReloadableServerResources, $ServerAdvancementManager, $ServerFunctionLibrary, $ServerFunctionManager, $ServerInfo, $ServerLinks, $ServerLinks$Entry, $ServerLinks$KnownLinkType, $ServerLinks$UntrustedEntry, $ServerScoreboard, $ServerTickRateManager, $Services, $TickTask, $WorldLoader$PackConfig, $WorldStem } from "java:net/minecraft/server";
import { $CustomBossEvent, $CustomBossEvents } from "java:net/minecraft/server/bossevents";
import { $ChunkGenerationTask, $ChunkHolder, $ChunkHolder$PlayerProvider, $ChunkMap, $ChunkResult, $ChunkTaskPriorityQueueSorter$Message, $ChunkTrackingView, $ClientInformation, $DistanceManager, $FullChunkStatus, $GeneratingChunkMap, $GenerationChunkHolder, $ServerBossEvent, $ServerChunkCache, $ServerEntity, $ServerLevel, $ServerPlayer, $ServerPlayer$RespawnPosAngle, $ServerPlayerGameMode, $ThreadedLevelLightEngine, $TicketType, $WorldGenRegion } from "java:net/minecraft/server/level";
import { $ChunkProgressListener, $StoringChunkProgressListener } from "java:net/minecraft/server/level/progress";
import { $CommonListenerCookie, $FilteredText, $PlayerChunkSender, $ServerCommonPacketListenerImpl, $ServerConnectionListener, $ServerGamePacketListenerImpl, $ServerPlayerConnection, $TextFilter } from "java:net/minecraft/server/network";
import { $PackLocationInfo, $PackResources, $PackResources$ResourceOutput, $PackSelectionConfig, $PackType, $VanillaPackResources } from "java:net/minecraft/server/packs";
import { $MetadataSectionSerializer, $MetadataSectionType } from "java:net/minecraft/server/packs/metadata";
import { $PackMetadataSection } from "java:net/minecraft/server/packs/metadata/pack";
import { $KnownPack, $Pack, $Pack$Metadata, $Pack$Position, $Pack$ResourcesSupplier, $PackCompatibility, $PackRepository, $PackSource, $RepositorySource } from "java:net/minecraft/server/packs/repository";
import { $CloseableResourceManager, $IoSupplier, $PreparableReloadListener, $PreparableReloadListener$PreparationBarrier, $Resource, $ResourceManager, $ResourceManagerReloadListener, $ResourceMetadata, $ResourceProvider, $SimpleJsonResourceReloadListener, $SimplePreparableReloadListener } from "java:net/minecraft/server/packs/resources";
import { $BanListEntry, $GameProfileCache, $GameProfileCache$GameProfileInfo, $IpBanList, $IpBanListEntry, $PlayerList, $ServerOpList, $StoredUserEntry, $StoredUserList, $UserBanList, $UserWhiteList } from "java:net/minecraft/server/players";
import { $Music, $SoundEvent, $SoundSource } from "java:net/minecraft/sounds";
import { $RecipeBook, $RecipeBookSettings, $ServerRecipeBook, $ServerStatsCounter, $Stat, $StatFormatter, $StatType, $StatsCounter } from "java:net/minecraft/stats";
import { $TagKey, $TagNetworkSerialization$NetworkPayload } from "java:net/minecraft/tags";
import { $AbortableIterationConsumer, $AbortableIterationConsumer$Continuation, $ArrayListDeque, $BitStorage, $FormattedCharSequence, $FormattedCharSink, $InclusiveRange, $KeyDispatchDataCodec, $ListAndDeque, $ModCheck, $ModCheck$Confidence, $OptionEnum, $ProblemReporter, $ProgressListener, $RandomSource, $SignatureUpdater, $SignatureUpdater$Output, $SignatureValidator, $StaticCache2D, $StaticCache2D$Initializer, $StringRepresentable, $StringRepresentable$EnumCodec, $StringRepresentable$StringRepresentableCodec, $TaskChainer, $Unit } from "java:net/minecraft/util";
import { $DataFixTypes } from "java:net/minecraft/util/datafix";
import { $AbstractSampleLogger, $LocalSampleLogger, $RemoteDebugSampleType, $SampleLogger, $SampleStorage } from "java:net/minecraft/util/debugchart";
import { $ProfileResults, $ProfilerFiller, $ResultField } from "java:net/minecraft/util/profiling";
import { $MetricCategory, $MetricSampler, $MetricSampler$MetricSamplerBuilder, $MetricSampler$SamplerResult, $MetricSampler$ThresholdTest, $ProfilerMeasured } from "java:net/minecraft/util/profiling/metrics";
import { $SimpleWeightedRandomList, $SimpleWeightedRandomList$Builder, $Weight, $WeightedEntry, $WeightedEntry$IntrusiveBase, $WeightedEntry$Wrapper, $WeightedRandomList } from "java:net/minecraft/util/random";
import { $BlockableEventLoop, $ProcessorHandle, $ReentrantBlockableEventLoop } from "java:net/minecraft/util/thread";
import { $BiasedToBottomInt, $ClampedInt, $ClampedNormalFloat, $ClampedNormalInt, $ConstantFloat, $ConstantInt, $FloatProvider, $FloatProviderType, $IntProvider, $IntProviderType, $SampledFloat, $TrapezoidFloat, $UniformFloat, $UniformInt, $WeightedListInt } from "java:net/minecraft/util/valueproviders";
import { $BossEvent, $BossEvent$BossBarColor, $BossEvent$BossBarOverlay, $Clearable, $Container, $ContainerListener, $Difficulty, $DifficultyInstance, $InteractionHand, $InteractionResult, $InteractionResultHolder, $ItemInteractionResult, $LockCode, $MenuProvider, $Nameable, $RandomSequence, $RandomSequences, $RandomizableContainer, $SimpleContainer, $TickRateManager, $WorldlyContainer } from "java:net/minecraft/world";
import { $CombatEntry, $CombatTracker, $DamageEffects, $DamageScaling, $DamageSource, $DamageSources, $DamageType, $DeathMessageType, $FallLocation } from "java:net/minecraft/world/damagesource";
import { $MobEffect, $MobEffect$AttributeTemplate, $MobEffectCategory, $MobEffectInstance } from "java:net/minecraft/world/effect";
import { $AgeableMob, $AnimationState, $AreaEffectCloud, $Attackable, $Crackiness$Level, $Display, $Display$BillboardConstraints, $Display$BlockDisplay, $Display$BlockDisplay$BlockRenderState, $Display$FloatInterpolator, $Display$GenericInterpolator, $Display$IntInterpolator, $Display$ItemDisplay, $Display$ItemDisplay$ItemRenderState, $Display$RenderState, $Display$TextDisplay, $Display$TextDisplay$Align, $Display$TextDisplay$CachedInfo, $Display$TextDisplay$CachedLine, $Display$TextDisplay$LineSplitter, $Display$TextDisplay$TextRenderState, $Entity, $Entity$RemovalReason, $EntityAttachment, $EntityAttachments, $EntityAttachments$Builder, $EntityDimensions, $EntityType, $EquipmentSlot, $EquipmentSlot$Type, $EquipmentSlotGroup, $EquipmentTable, $EquipmentUser, $ExperienceOrb, $FlyingMob, $GlowSquid, $HasCustomInventoryScreen, $HumanoidArm, $Interaction, $ItemSteerable, $Leashable, $Leashable$LeashData, $LerpingModel, $LightningBolt, $LivingEntity, $LivingEntity$Fallsounds, $Marker, $Mob, $MobCategory, $MobSpawnType, $MoverType, $NeutralMob, $OminousItemSpawner, $OwnableEntity, $PathfinderMob, $PlayerRideable, $PlayerRideableJumping, $PortalProcessor, $Pose, $PowerableMob, $RelativeMovement, $ReputationEventHandler, $Saddleable, $Shearable, $SlotAccess, $SpawnGroupData, $TamableAnimal, $Targeting, $TraceableEntity, $VariantHolder, $WalkAnimationState } from "java:net/minecraft/world/entity";
import { $Brain, $Brain$Provider } from "java:net/minecraft/world/entity/ai";
import { $Attribute, $Attribute$Sentiment, $AttributeInstance, $AttributeMap, $AttributeModifier, $AttributeModifier$Operation, $AttributeSupplier, $AttributeSupplier$Builder } from "java:net/minecraft/world/entity/ai/attributes";
import { $Behavior$Status, $BehaviorControl, $PositionTracker } from "java:net/minecraft/world/entity/ai/behavior";
import { $Control, $JumpControl, $LookControl, $MoveControl } from "java:net/minecraft/world/entity/ai/control";
import { $Goal, $Goal$Flag, $GoalSelector, $WrappedGoal } from "java:net/minecraft/world/entity/ai/goal";
import { $GossipContainer, $GossipType } from "java:net/minecraft/world/entity/ai/gossip";
import { $ExpirableValue, $MemoryModuleType, $MemoryStatus, $NearestVisibleLivingEntities, $WalkTarget } from "java:net/minecraft/world/entity/ai/memory";
import { $PathNavigation } from "java:net/minecraft/world/entity/ai/navigation";
import { $Sensing } from "java:net/minecraft/world/entity/ai/sensing";
import { $TargetingConditions } from "java:net/minecraft/world/entity/ai/targeting";
import { $ReputationEventType } from "java:net/minecraft/world/entity/ai/village";
import { $PoiManager, $PoiManager$Occupancy, $PoiRecord, $PoiType } from "java:net/minecraft/world/entity/ai/village/poi";
import { $AmbientCreature, $Bat } from "java:net/minecraft/world/entity/ambient";
import { $AbstractFish, $AbstractGolem, $AbstractSchoolingFish, $Animal, $Bee, $Bucketable, $Cat, $CatVariant, $Chicken, $Cod, $Cow, $Dolphin, $FlyingAnimal, $Fox, $Fox$Type, $FrogVariant, $IronGolem, $MushroomCow, $MushroomCow$MushroomType, $Ocelot, $Panda, $Panda$Gene, $Parrot, $Parrot$Variant, $Pig, $PolarBear, $Pufferfish, $Rabbit, $Rabbit$Variant, $Salmon, $Sheep, $ShoulderRidingEntity, $SnowGolem, $Squid, $TropicalFish, $TropicalFish$Base, $TropicalFish$Pattern, $TropicalFish$Variant, $Turtle, $WaterAnimal, $Wolf, $WolfVariant } from "java:net/minecraft/world/entity/animal";
import { $Allay } from "java:net/minecraft/world/entity/animal/allay";
import { $Armadillo, $Armadillo$ArmadilloState } from "java:net/minecraft/world/entity/animal/armadillo";
import { $Axolotl, $Axolotl$Variant } from "java:net/minecraft/world/entity/animal/axolotl";
import { $Camel } from "java:net/minecraft/world/entity/animal/camel";
import { $Frog, $Tadpole } from "java:net/minecraft/world/entity/animal/frog";
import { $Goat } from "java:net/minecraft/world/entity/animal/goat";
import { $AbstractChestedHorse, $AbstractHorse, $Donkey, $Horse, $Llama, $Llama$Variant, $Markings, $Mule, $SkeletonHorse, $TraderLlama, $Variant, $ZombieHorse } from "java:net/minecraft/world/entity/animal/horse";
import { $Sniffer, $Sniffer$State } from "java:net/minecraft/world/entity/animal/sniffer";
import { $EnderDragonPart } from "java:net/minecraft/world/entity/boss";
import { $EndCrystal, $EnderDragon } from "java:net/minecraft/world/entity/boss/enderdragon";
import { $AbstractDragonPhaseInstance, $AbstractDragonSittingPhase, $DragonChargePlayerPhase, $DragonDeathPhase, $DragonHoldingPatternPhase, $DragonHoverPhase, $DragonLandingApproachPhase, $DragonLandingPhase, $DragonPhaseInstance, $DragonSittingAttackingPhase, $DragonSittingFlamingPhase, $DragonSittingScanningPhase, $DragonStrafePlayerPhase, $DragonTakeoffPhase, $EnderDragonPhase, $EnderDragonPhaseManager } from "java:net/minecraft/world/entity/boss/enderdragon/phases";
import { $WitherBoss } from "java:net/minecraft/world/entity/boss/wither";
import { $ArmorStand, $BlockAttachedEntity, $GlowItemFrame, $HangingEntity, $ItemFrame, $LeashFenceKnotEntity, $Painting, $PaintingVariant } from "java:net/minecraft/world/entity/decoration";
import { $FallingBlockEntity, $ItemEntity, $PrimedTnt } from "java:net/minecraft/world/entity/item";
import { $AbstractIllager, $AbstractIllager$IllagerArmPose, $AbstractSkeleton, $Blaze, $Bogged, $CaveSpider, $Creeper, $CrossbowAttackMob, $Drowned, $ElderGuardian, $EnderMan, $Endermite, $Enemy, $Evoker, $Ghast, $Giant, $Guardian, $Husk, $Illusioner, $MagmaCube, $Monster, $PatrollingMonster, $Phantom, $Pillager, $RangedAttackMob, $Ravager, $Shulker, $Silverfish, $Skeleton, $Slime, $SpellcasterIllager, $SpellcasterIllager$IllagerSpell, $Spider, $Stray, $Strider, $Vex, $Vindicator, $Witch, $WitherSkeleton, $Zoglin, $Zombie, $ZombieVillager, $ZombifiedPiglin } from "java:net/minecraft/world/entity/monster";
import { $Breeze } from "java:net/minecraft/world/entity/monster/breeze";
import { $Hoglin, $HoglinBase } from "java:net/minecraft/world/entity/monster/hoglin";
import { $AbstractPiglin, $Piglin, $PiglinArmPose, $PiglinBrute } from "java:net/minecraft/world/entity/monster/piglin";
import { $AngerLevel, $AngerManagement, $Warden, $WardenSpawnTracker } from "java:net/minecraft/world/entity/monster/warden";
import { $AbstractVillager, $InventoryCarrier, $Npc, $Villager, $VillagerData, $VillagerDataHolder, $VillagerProfession, $VillagerType, $WanderingTrader } from "java:net/minecraft/world/entity/npc";
import { $Abilities, $ChatVisiblity, $Inventory, $Player, $Player$BedSleepingProblem, $PlayerModelPart, $ProfileKeyPair, $ProfilePublicKey, $ProfilePublicKey$Data, $StackedContents } from "java:net/minecraft/world/entity/player";
import { $AbstractArrow, $AbstractArrow$Pickup, $AbstractHurtingProjectile, $Arrow, $DragonFireball, $EvokerFangs, $EyeOfEnder, $Fireball, $FireworkRocketEntity, $FishingHook, $ItemSupplier, $LargeFireball, $LlamaSpit, $Projectile, $ProjectileDeflection, $ShulkerBullet, $SmallFireball, $Snowball, $SpectralArrow, $ThrowableItemProjectile, $ThrowableProjectile, $ThrownEgg, $ThrownEnderpearl, $ThrownExperienceBottle, $ThrownPotion, $ThrownTrident, $WitherSkull } from "java:net/minecraft/world/entity/projectile";
import { $AbstractWindCharge, $BreezeWindCharge, $WindCharge } from "java:net/minecraft/world/entity/projectile/windcharge";
import { $Raid, $Raider, $Raids } from "java:net/minecraft/world/entity/raid";
import { $Activity, $Schedule } from "java:net/minecraft/world/entity/schedule";
import { $AbstractMinecart, $AbstractMinecart$Type, $AbstractMinecartContainer, $Boat, $Boat$Type, $ChestBoat, $ContainerEntity, $Minecart, $MinecartChest, $MinecartCommandBlock, $MinecartFurnace, $MinecartHopper, $MinecartSpawner, $MinecartTNT, $VehicleEntity } from "java:net/minecraft/world/entity/vehicle";
import { $FeatureElement, $FeatureFlag, $FeatureFlagSet } from "java:net/minecraft/world/flag";
import { $FoodData, $FoodProperties, $FoodProperties$PossibleEffect } from "java:net/minecraft/world/food";
import { $AbstractContainerMenu, $AbstractFurnaceMenu, $AnvilMenu, $BeaconMenu, $BlastFurnaceMenu, $BrewingStandMenu, $CartographyTableMenu, $ChestMenu, $ClickAction, $ClickType, $ContainerListener, $ContainerSynchronizer, $CrafterMenu, $CraftingContainer, $CraftingMenu, $DispenserMenu, $EnchantmentMenu, $FurnaceMenu, $GrindstoneMenu, $HopperMenu, $InventoryMenu, $ItemCombinerMenu, $LecternMenu, $LoomMenu, $MenuConstructor, $MenuType, $MenuType$MenuSupplier, $MerchantMenu, $PlayerEnderChestContainer, $RecipeBookMenu, $RecipeBookType, $RecipeCraftingHolder, $ShulkerBoxMenu, $Slot, $SmithingMenu, $SmokerMenu, $StackedContentsCompatible, $StonecutterMenu } from "java:net/minecraft/world/inventory";
import { $TooltipComponent } from "java:net/minecraft/world/inventory/tooltip";
import { $ArmorMaterial$Layer, $DyeColor, $Item, $Item$TooltipContext, $ItemCooldowns, $ItemDisplayContext, $ItemStack, $JukeboxSong, $JukeboxSongPlayer, $ProjectileWeaponItem, $Rarity, $TooltipFlag, $TooltipFlag$Default, $UseAnim } from "java:net/minecraft/world/item";
import { $Potion, $PotionBrewing, $PotionBrewing$Builder, $PotionContents } from "java:net/minecraft/world/item/alchemy";
import { $CustomData, $FireworkExplosion, $FireworkExplosion$Shape, $ItemAttributeModifiers, $ItemAttributeModifiers$Builder, $ItemAttributeModifiers$Entry, $ResolvableProfile, $TooltipProvider } from "java:net/minecraft/world/item/component";
import { $BlockPlaceContext, $UseOnContext } from "java:net/minecraft/world/item/context";
import { $AbstractCookingRecipe, $ArmorDyeRecipe, $BannerDuplicateRecipe, $BlastingRecipe, $BookCloningRecipe, $CampfireCookingRecipe, $CookingBookCategory, $CraftingBookCategory, $CraftingInput, $CraftingInput$Positioned, $CraftingRecipe, $CustomRecipe, $DecoratedPotRecipe, $FireworkRocketRecipe, $FireworkStarFadeRecipe, $FireworkStarRecipe, $Ingredient, $Ingredient$Value, $MapCloningRecipe, $MapExtendingRecipe, $Recipe, $RecipeHolder, $RecipeInput, $RecipeManager, $RecipeManager$CachedCheck, $RecipeSerializer, $RecipeType, $RepairItemRecipe, $ShapedRecipe, $ShapedRecipePattern, $ShapelessRecipe, $ShieldDecorationRecipe, $ShulkerBoxColoring, $SingleItemRecipe, $SingleRecipeInput, $SmeltingRecipe, $SmithingRecipe, $SmithingRecipeInput, $SmithingTransformRecipe, $SmithingTrimRecipe, $SmokingRecipe, $StonecutterRecipe, $SuspiciousStewRecipe, $TippedArrowRecipe } from "java:net/minecraft/world/item/crafting";
import { $ConditionalEffect, $EnchantedItemInUse, $Enchantment, $Enchantment$Builder, $Enchantment$Cost, $Enchantment$EnchantmentDefinition, $EnchantmentInstance, $EnchantmentTarget, $ItemEnchantments, $LevelBasedValue, $LevelBasedValue$Constant, $LevelBasedValue$Linear, $LevelBasedValue$Lookup, $TargetedConditionalEffect } from "java:net/minecraft/world/item/enchantment";
import { $EnchantmentAttributeEffect, $EnchantmentEntityEffect, $EnchantmentLocationBasedEffect, $EnchantmentValueEffect } from "java:net/minecraft/world/item/enchantment/effects";
import { $ItemCost, $Merchant, $MerchantOffer, $MerchantOffers } from "java:net/minecraft/world/item/trading";
import { $BaseCommandBlock, $BaseSpawner, $BlockAndTintGetter, $BlockGetter, $ChunkPos, $ClipBlockStateContext, $ClipContext, $ClipContext$Fluid, $CollisionGetter, $ColorResolver, $CommonLevelAccessor, $DataPackConfig, $EntityGetter, $Explosion, $Explosion$BlockInteraction, $ExplosionDamageCalculator, $GameRules, $GameRules$BooleanValue, $GameRules$Category, $GameRules$GameRuleTypeVisitor, $GameRules$IntegerValue, $GameRules$Key, $GameRules$Type, $GameRules$Value, $GameType, $ItemLike, $Level, $Level$ExplosionInteraction, $LevelAccessor, $LevelHeightAccessor, $LevelReader, $LevelSettings, $LevelSimulatedRW, $LevelSimulatedReader, $LevelTimeAccess, $LevelWriter, $LightLayer, $NaturalSpawner$SpawnState, $NoiseColumn, $PathNavigationRegion, $ServerLevelAccessor, $SignalGetter, $SpawnData, $SpawnData$CustomSpawnRules, $Spawner, $StructureManager, $WorldDataConfiguration, $WorldGenLevel } from "java:net/minecraft/world/level";
import { $AmbientAdditionsSettings, $AmbientMoodSettings, $AmbientParticleSettings, $Biome, $Biome$ClimateSettings, $Biome$Precipitation, $Biome$TemperatureModifier, $BiomeGenerationSettings, $BiomeGenerationSettings$PlainBuilder, $BiomeManager, $BiomeManager$NoiseBiomeSource, $BiomeResolver, $BiomeSource, $BiomeSpecialEffects, $BiomeSpecialEffects$Builder, $BiomeSpecialEffects$GrassColorModifier, $Climate$Parameter, $Climate$ParameterPoint, $Climate$Sampler, $Climate$TargetPoint, $MobSpawnSettings, $MobSpawnSettings$Builder, $MobSpawnSettings$MobSpawnCost, $MobSpawnSettings$SpawnerData } from "java:net/minecraft/world/level/biome";
import { $Block, $Mirror, $Portal, $Portal$Transition, $RenderShape, $Rotation, $SculkSpreader, $SculkSpreader$ChargeCursor, $SoundType, $SupportType } from "java:net/minecraft/world/level/block";
import { $AbstractFurnaceBlockEntity, $BannerBlockEntity, $BannerPattern, $BannerPatternLayers, $BannerPatternLayers$Layer, $BarrelBlockEntity, $BaseContainerBlockEntity, $BeaconBlockEntity, $BeaconBlockEntity$BeaconBeamSection, $BedBlockEntity, $BeehiveBlockEntity, $BeehiveBlockEntity$BeeReleaseStatus, $BeehiveBlockEntity$Occupant, $BellBlockEntity, $BlastFurnaceBlockEntity, $BlockEntity, $BlockEntityTicker, $BlockEntityType, $BrewingStandBlockEntity, $BrushableBlockEntity, $CalibratedSculkSensorBlockEntity, $CampfireBlockEntity, $ChestBlockEntity, $ChiseledBookShelfBlockEntity, $CommandBlockEntity, $CommandBlockEntity$Mode, $ComparatorBlockEntity, $ConduitBlockEntity, $CrafterBlockEntity, $DaylightDetectorBlockEntity, $DecoratedPotBlockEntity, $DecoratedPotBlockEntity$WobbleStyle, $DispenserBlockEntity, $DropperBlockEntity, $EnchantingTableBlockEntity, $EnderChestBlockEntity, $FurnaceBlockEntity, $HangingSignBlockEntity, $Hopper, $HopperBlockEntity, $JigsawBlockEntity, $JigsawBlockEntity$JointType, $JukeboxBlockEntity, $LecternBlockEntity, $LidBlockEntity, $PotDecorations, $RandomizableContainerBlockEntity, $SculkCatalystBlockEntity, $SculkCatalystBlockEntity$CatalystListener, $SculkSensorBlockEntity, $SculkShriekerBlockEntity, $ShulkerBoxBlockEntity, $ShulkerBoxBlockEntity$AnimationStatus, $SignBlockEntity, $SignText, $SkullBlockEntity, $SmokerBlockEntity, $SpawnerBlockEntity, $StructureBlockEntity, $StructureBlockEntity$UpdateType, $TheEndGatewayBlockEntity, $TheEndPortalBlockEntity, $TickingBlockEntity, $TrappedChestBlockEntity, $TrialSpawnerBlockEntity } from "java:net/minecraft/world/level/block/entity";
import { $PlayerDetector, $PlayerDetector$EntitySelector, $TrialSpawner, $TrialSpawner$StateAccessor, $TrialSpawnerConfig, $TrialSpawnerData, $TrialSpawnerState } from "java:net/minecraft/world/level/block/entity/trialspawner";
import { $VaultBlockEntity, $VaultClientData, $VaultConfig, $VaultServerData, $VaultSharedData } from "java:net/minecraft/world/level/block/entity/vault";
import { $PistonMovingBlockEntity } from "java:net/minecraft/world/level/block/piston";
import { $BlockBehaviour, $BlockBehaviour$BlockStateBase, $BlockBehaviour$OffsetType, $BlockBehaviour$Properties, $BlockBehaviour$StateArgumentPredicate, $BlockBehaviour$StatePredicate, $BlockState, $StateDefinition, $StateHolder } from "java:net/minecraft/world/level/block/state";
import { $BlockInWorld } from "java:net/minecraft/world/level/block/state/pattern";
import { $BooleanProperty, $NoteBlockInstrument, $Property, $Property$Value, $StructureMode } from "java:net/minecraft/world/level/block/state/properties";
import { $BorderChangeListener, $BorderStatus, $WorldBorder, $WorldBorder$Settings } from "java:net/minecraft/world/level/border";
import { $BlockColumn, $CarvingMask, $CarvingMask$Mask, $ChunkAccess, $ChunkAccess$TicksToSave, $ChunkGenerator, $ChunkGeneratorStructureState, $ChunkSource, $DataLayer, $ImposterProtoChunk, $LevelChunk, $LevelChunk$EntityCreationType, $LevelChunkSection, $LightChunk, $LightChunkGetter, $Palette, $Palette$Factory, $PaletteResize, $PalettedContainer, $PalettedContainer$Configuration, $PalettedContainer$CountConsumer, $PalettedContainer$Data, $PalettedContainer$Strategy, $PalettedContainerRO, $PalettedContainerRO$PackedData, $ProtoChunk, $StructureAccess, $UpgradeData } from "java:net/minecraft/world/level/chunk";
import { $ChunkDependencies, $ChunkStatus, $ChunkStatusTask, $ChunkStep, $ChunkType, $WorldGenContext } from "java:net/minecraft/world/level/chunk/status";
import { $ChunkIOErrorReporter, $ChunkScanAccess, $ChunkStorage, $RegionStorageInfo, $SectionStorage } from "java:net/minecraft/world/level/chunk/storage";
import { $DimensionType, $DimensionType$MonsterSettings, $LevelStem } from "java:net/minecraft/world/level/dimension";
import { $EndDragonFight, $EndDragonFight$Data } from "java:net/minecraft/world/level/dimension/end";
import { $EntityAccess, $EntityInLevelCallback, $EntityTypeTest, $LevelEntityGetter } from "java:net/minecraft/world/level/entity";
import { $BlockPositionSource, $DynamicGameEventListener, $EntityPositionSource, $GameEvent, $GameEvent$Context, $GameEventListener, $GameEventListener$DeliveryMode, $GameEventListener$Provider, $GameEventListenerRegistry, $GameEventListenerRegistry$ListenerVisitor, $PositionSource, $PositionSourceType } from "java:net/minecraft/world/level/gameevent";
import { $VibrationInfo, $VibrationSelector, $VibrationSystem, $VibrationSystem$Data, $VibrationSystem$Listener, $VibrationSystem$User } from "java:net/minecraft/world/level/gameevent/vibrations";
import { $Aquifer, $Aquifer$FluidPicker, $Aquifer$FluidStatus, $BelowZeroRetrogen, $BitRandomSource, $DensityFunction, $DensityFunction$ContextProvider, $DensityFunction$FunctionContext, $DensityFunction$NoiseHolder, $DensityFunction$SimpleFunction, $DensityFunction$Visitor, $DensityFunctions$BeardifierOrMarker, $GenerationStep$Carving, $GenerationStep$Decoration, $Heightmap, $Heightmap$Types, $LegacyRandomSource, $NoiseChunk, $NoiseGeneratorSettings, $NoiseRouter, $NoiseSettings, $PositionalRandomFactory, $RandomState, $RandomSupport$Seed128bit, $SurfaceRules$RuleSource, $SurfaceSystem, $VerticalAnchor, $WorldDimensions, $WorldDimensions$Complete, $WorldGenerationContext, $WorldOptions, $WorldgenRandom, $WorldgenRandom$Algorithm } from "java:net/minecraft/world/level/levelgen";
import { $Blender, $Blender$BlendingOutput, $Blender$DistanceGetter, $BlendingData } from "java:net/minecraft/world/level/levelgen/blending";
import { $AllOfPredicate, $AnyOfPredicate, $BlockPredicate, $BlockPredicateType, $CombiningPredicate, $HasSturdyFacePredicate, $InsideWorldBoundsPredicate, $MatchingBlockTagPredicate, $MatchingBlocksPredicate, $MatchingFluidsPredicate, $NotPredicate, $ReplaceablePredicate, $SolidPredicate, $StateTestingPredicate, $TrueBlockPredicate, $UnobstructedPredicate, $WouldSurvivePredicate } from "java:net/minecraft/world/level/levelgen/blockpredicates";
import { $CanyonCarverConfiguration, $CanyonCarverConfiguration$CanyonShapeConfiguration, $CarverConfiguration, $CarverDebugSettings, $CarvingContext, $CaveCarverConfiguration, $ConfiguredWorldCarver, $WorldCarver } from "java:net/minecraft/world/level/levelgen/carver";
import { $ConfiguredFeature } from "java:net/minecraft/world/level/levelgen/feature";
import { $FeatureConfiguration, $NoneFeatureConfiguration, $ProbabilityFeatureConfiguration, $TreeConfiguration } from "java:net/minecraft/world/level/levelgen/feature/configurations";
import { $FeatureSize } from "java:net/minecraft/world/level/levelgen/feature/featuresize";
import { $FoliagePlacer, $FoliagePlacer$FoliageAttachment, $FoliagePlacer$FoliageSetter } from "java:net/minecraft/world/level/levelgen/feature/foliageplacers";
import { $RootPlacer } from "java:net/minecraft/world/level/levelgen/feature/rootplacers";
import { $BlockStateProvider, $SimpleStateProvider } from "java:net/minecraft/world/level/levelgen/feature/stateproviders";
import { $TreeDecorator, $TreeDecorator$Context } from "java:net/minecraft/world/level/levelgen/feature/treedecorators";
import { $TrunkPlacer } from "java:net/minecraft/world/level/levelgen/feature/trunkplacers";
import { $BiasedToBottomHeight, $ConstantHeight, $HeightProvider, $HeightProviderType, $TrapezoidHeight, $UniformHeight, $VeryBiasedToBottomHeight, $WeightedListHeight } from "java:net/minecraft/world/level/levelgen/heightproviders";
import { $BiomeFilter, $BlockPredicateFilter, $CarvingMaskPlacement, $CountOnEveryLayerPlacement, $CountPlacement, $EnvironmentScanPlacement, $FixedPlacement, $HeightRangePlacement, $HeightmapPlacement, $InSquarePlacement, $NoiseBasedCountPlacement, $NoiseThresholdCountPlacement, $PlacedFeature, $PlacementContext, $PlacementFilter, $PlacementModifier, $PlacementModifierType, $RandomOffsetPlacement, $RarityFilter, $RepeatingPlacement, $SurfaceRelativeThresholdFilter, $SurfaceWaterDepthFilter } from "java:net/minecraft/world/level/levelgen/placement";
import { $WorldPreset } from "java:net/minecraft/world/level/levelgen/presets";
import { $BoundingBox, $SinglePieceStructure, $Structure, $Structure$GenerationContext, $Structure$GenerationStub, $Structure$StructureSettings, $StructureCheckResult, $StructurePiece, $StructurePieceAccessor, $StructureSet, $StructureSet$StructureSelectionEntry, $StructureSpawnOverride, $StructureSpawnOverride$BoundingBoxType, $StructureStart, $StructureType, $TerrainAdjustment } from "java:net/minecraft/world/level/levelgen/structure";
import { $PiecesContainer, $StructurePieceSerializationContext, $StructurePieceType, $StructurePiecesBuilder } from "java:net/minecraft/world/level/levelgen/structure/pieces";
import { $ConcentricRingsStructurePlacement, $RandomSpreadStructurePlacement, $RandomSpreadType, $StructurePlacement, $StructurePlacementType } from "java:net/minecraft/world/level/levelgen/structure/placement";
import { $DimensionPadding, $EmptyPoolElement, $FeaturePoolElement, $LegacySinglePoolElement, $ListPoolElement, $SinglePoolElement, $StructurePoolElement, $StructurePoolElementType, $StructureTemplatePool, $StructureTemplatePool$Projection } from "java:net/minecraft/world/level/levelgen/structure/pools";
import { $BuriedTreasureStructure, $DesertPyramidStructure, $EndCityStructure, $IglooStructure, $JigsawStructure, $JungleTempleStructure, $MineshaftStructure, $NetherFortressStructure, $NetherFossilStructure, $OceanMonumentStructure, $OceanRuinStructure, $OceanRuinStructure$Type, $RuinedPortalStructure, $ShipwreckStructure, $StrongholdStructure, $SwampHutStructure, $WoodlandMansionStructure } from "java:net/minecraft/world/level/levelgen/structure/structures";
import { $LiquidSettings, $StructurePlaceSettings, $StructureProcessor, $StructureProcessorList, $StructureTemplate, $StructureTemplate$Palette, $StructureTemplate$StructureBlockInfo, $StructureTemplate$StructureEntityInfo, $StructureTemplateManager } from "java:net/minecraft/world/level/levelgen/structure/templatesystem";
import { $NormalNoise, $NormalNoise$NoiseParameters, $PerlinSimplexNoise } from "java:net/minecraft/world/level/levelgen/synth";
import { $ChunkSkyLightSources, $LayerLightEventListener, $LayerLightSectionStorage$SectionType, $LevelLightEngine, $LightEventListener } from "java:net/minecraft/world/level/lighting";
import { $Fluid, $FluidState, $FogType, $MapColor, $MapColor$Brightness, $PushReaction } from "java:net/minecraft/world/level/material";
import { $Node, $NodeEvaluator, $Path, $Path$DebugData, $PathComputationType, $PathType, $PathTypeCache, $PathfindingContext, $Target } from "java:net/minecraft/world/level/pathfinder";
import { $DimensionTransition, $DimensionTransition$PostDimensionTransition, $PortalForcer, $PortalShape } from "java:net/minecraft/world/level/portal";
import { $SavedData, $SavedData$Factory } from "java:net/minecraft/world/level/saveddata";
import { $MapBanner, $MapDecoration, $MapDecorationType, $MapId, $MapItemSavedData, $MapItemSavedData$HoldingPlayer, $MapItemSavedData$MapPatch } from "java:net/minecraft/world/level/saveddata/maps";
import { $CommandStorage, $DataVersion, $DimensionDataStorage, $LevelData, $LevelDataAndDimensions, $LevelResource, $LevelStorageSource, $LevelStorageSource$LevelCandidates, $LevelStorageSource$LevelDirectory, $LevelStorageSource$LevelStorageAccess, $LevelSummary, $LevelSummary$BackupStatus, $LevelVersion, $PlayerDataStorage, $PrimaryLevelData$SpecialWorldProperty, $ServerLevelData, $WorldData, $WritableLevelData } from "java:net/minecraft/world/level/storage";
import { $LootContext, $LootContext$VisitedEntry, $LootContextUser, $LootDataType, $LootDataType$Validator, $LootParams, $LootParams$Builder, $LootParams$DynamicDrop, $LootPool, $LootPool$Builder, $LootTable, $LootTable$Builder, $ValidationContext } from "java:net/minecraft/world/level/storage/loot";
import { $AlternativesEntry$Builder, $ComposableEntryContainer, $EntryGroup$Builder, $LootPoolEntry, $LootPoolEntryContainer, $LootPoolEntryContainer$Builder, $LootPoolEntryType, $SequentialEntry$Builder } from "java:net/minecraft/world/level/storage/loot/entries";
import { $FunctionUserBuilder, $LootItemFunction, $LootItemFunction$Builder, $LootItemFunctionType } from "java:net/minecraft/world/level/storage/loot/functions";
import { $LootContextParam, $LootContextParamSet, $LootContextParamSet$Builder } from "java:net/minecraft/world/level/storage/loot/parameters";
import { $AllOfCondition$Builder, $AnyOfCondition$Builder, $CompositeLootItemCondition$Builder, $ConditionUserBuilder, $LootItemCondition, $LootItemCondition$Builder, $LootItemConditionType } from "java:net/minecraft/world/level/storage/loot/predicates";
import { $LootNumberProviderType, $NumberProvider } from "java:net/minecraft/world/level/storage/loot/providers/number";
import { $TimerCallback, $TimerQueue } from "java:net/minecraft/world/level/timers";
import { $DirectoryValidator, $ForbiddenSymlinkInfo } from "java:net/minecraft/world/level/validation";
import { $AABB, $BlockHitResult, $EntityHitResult, $HitResult, $HitResult$Type, $Vec2, $Vec3 } from "java:net/minecraft/world/phys";
import { $CollisionContext, $DiscreteVoxelShape, $DiscreteVoxelShape$IntFaceConsumer, $DiscreteVoxelShape$IntLineConsumer, $Shapes$DoubleLineConsumer, $VoxelShape } from "java:net/minecraft/world/phys/shapes";
import { $DisplaySlot, $Objective, $PlayerScoreEntry, $PlayerTeam, $ReadOnlyScoreInfo, $ScoreAccess, $ScoreHolder, $Scoreboard, $ScoreboardSaveData, $Team, $Team$CollisionRule, $Team$Visibility } from "java:net/minecraft/world/scores";
import { $ObjectiveCriteria, $ObjectiveCriteria$RenderType } from "java:net/minecraft/world/scores/criteria";
import { $ContainerSingleItem, $ContainerSingleItem$BlockContainerSingleItem, $LevelChunkTicks, $LevelTickAccess, $LevelTicks, $ScheduledTick, $SerializableTickContainer, $TickAccess, $TickContainerAccess, $TickPriority } from "java:net/minecraft/world/ticks";
import { $Event, $ICancellableEvent } from "java:net/neoforged/bus/api";
import { $LogicalSide } from "java:net/neoforged/fml";
import { $ExtensionInfo, $IExtensibleEnum, $NetworkedEnum$NetworkCheck } from "java:net/neoforged/fml/common/asm/enumextension";
import { $IModBusEvent } from "java:net/neoforged/fml/event";
import { $AttachmentHolder, $AttachmentHolder$AsField, $AttachmentSyncHandler, $AttachmentType, $AttachmentType$Builder, $IAttachmentCopyHandler, $IAttachmentHolder, $IAttachmentSerializer } from "java:net/neoforged/neoforge/attachment";
import { $BaseCapability, $BlockCapability, $EntityCapability, $IBlockCapabilityProvider, $ICapabilityInvalidationListener, $ICapabilityProvider, $ItemCapability, $RegisterCapabilitiesEvent } from "java:net/neoforged/neoforge/capabilities";
import { $ChunkRenderTypeSet, $ExtendedServerListData, $RenderTypeGroup } from "java:net/neoforged/neoforge/client";
import { $ClientPlayerNetworkEvent, $ClientPlayerNetworkEvent$Clone, $ClientPlayerNetworkEvent$LoggingIn, $ClientPlayerNetworkEvent$LoggingOut, $ClientTickEvent, $ClientTickEvent$Post, $ClientTickEvent$Pre, $EntityRenderersEvent, $EntityRenderersEvent$RegisterRenderers, $InputEvent, $InputEvent$InteractionKeyMappingTriggered, $RegisterClientCommandsEvent, $RegisterKeyMappingsEvent, $RegisterMenuScreensEvent, $RegisterParticleProvidersEvent } from "java:net/neoforged/neoforge/client/event";
import { $IAbstractWidgetExtension, $IBakedModelExtension, $IBlockEntityRendererExtension, $IDimensionSpecialEffectsExtension, $IFontExtension, $IGuiGraphicsExtension, $IKeyMappingExtension, $IMenuProviderExtension, $IMinecraftExtension, $IModelBakerExtension, $IPoseStackExtension, $IVertexConsumerExtension, $ModelStateExtension } from "java:net/neoforged/neoforge/client/extensions";
import { $IClientBlockExtensions, $IClientFluidTypeExtensions, $IClientItemExtensions, $IClientItemExtensions$FontContext, $IClientMobEffectExtensions } from "java:net/neoforged/neoforge/client/extensions/common";
import { $ExtraFaceData } from "java:net/neoforged/neoforge/client/model";
import { $ModelData, $ModelData$Builder, $ModelDataManager, $ModelProperty } from "java:net/neoforged/neoforge/client/model/data";
import { $BlockGeometryBakingContext, $BlockGeometryBakingContext$VisibilityData, $IGeometryBakingContext, $IUnbakedGeometry } from "java:net/neoforged/neoforge/client/model/geometry";
import { $IKeyConflictContext, $KeyModifier } from "java:net/neoforged/neoforge/client/settings";
import { $EffectCure, $IMinecartCollisionHandler, $IShearable, $ItemAbility, $MutableDataComponentHolder, $SoundAction } from "java:net/neoforged/neoforge/common";
import { $IBrewingRecipe } from "java:net/neoforged/neoforge/common/brewing";
import { $ICondition, $ICondition$IContext, $WithConditions, $WithConditions$Builder } from "java:net/neoforged/neoforge/common/conditions";
import { $ICustomIngredient, $IngredientType } from "java:net/neoforged/neoforge/common/crafting";
import { $DamageContainer, $DamageContainer$Reduction, $IDeathMessageProvider, $IReductionFunction, $IScalingFunction } from "java:net/neoforged/neoforge/common/damagesource";
import { $BubbleColumnDirection } from "java:net/neoforged/neoforge/common/enums";
import { $IAbstractMinecartExtension, $IAttributeExtension, $IBlockAndTintGetterExtension, $IBlockEntityExtension, $IBlockExtension, $IBlockGetterExtension, $IBlockStateExtension, $IBoatExtension, $IClientCommonPacketListenerExtension, $ICommandSourceStackExtension, $ICommonPacketListener, $IDataComponentHolderExtension, $IDataComponentMapBuilderExtensions, $IEntityExtension, $IFluidExtension, $IFluidStateExtension, $IFriendlyByteBufExtension, $IHolderExtension, $IHolderLookupProviderExtension, $IHolderSetExtension, $IHolderSetExtension$SerializationType, $IItemExtension, $IItemStackExtension, $ILevelExtension, $ILevelReaderExtension, $ILivingEntityExtension, $IMenuTypeExtension, $IMobEffectExtension, $IOwnedSpawner, $IPackResourcesExtension, $IPacketFlowExtension, $IPlayerExtension, $IServerChunkCacheExtension, $IServerCommonPacketListenerExtension, $IServerGamePacketListenerExtension, $ITransformationExtension } from "java:net/neoforged/neoforge/common/extensions";
import { $BlockSnapshot, $INBTSerializable, $Lazy, $TriState } from "java:net/neoforged/neoforge/common/util";
import { $AuxiliaryLightManager, $BiomeGenerationSettingsBuilder, $BiomeModifier, $BiomeModifier$Phase, $BiomeSpecialEffectsBuilder, $ClimateSettingsBuilder, $LevelChunkAuxiliaryLightManager, $MobSpawnSettingsBuilder, $ModifiableBiomeInfo, $ModifiableBiomeInfo$BiomeInfo, $ModifiableBiomeInfo$BiomeInfo$Builder, $ModifiableStructureInfo, $ModifiableStructureInfo$StructureInfo, $ModifiableStructureInfo$StructureInfo$Builder, $StructureModifier, $StructureModifier$Phase, $StructureSettingsBuilder, $StructureSettingsBuilder$StructureSpawnOverrideBuilder } from "java:net/neoforged/neoforge/common/world";
import { $PartEntity } from "java:net/neoforged/neoforge/entity";
import { $CommandEvent, $LootTableLoadEvent, $OnDatapackSyncEvent, $RegisterCommandsEvent, $ServerChatEvent, $TagsUpdatedEvent, $TagsUpdatedEvent$UpdateCause } from "java:net/neoforged/neoforge/event";
import { $EntityEvent, $EntityJoinLevelEvent, $EntityLeaveLevelEvent } from "java:net/neoforged/neoforge/event/entity";
import { $ItemEvent, $ItemTossEvent } from "java:net/neoforged/neoforge/event/entity/item";
import { $FinalizeSpawnEvent, $LivingDamageEvent, $LivingDamageEvent$Post, $LivingDamageEvent$Pre, $LivingDeathEvent, $LivingDropsEvent, $LivingEntityUseItemEvent, $LivingEntityUseItemEvent$Finish, $LivingEntityUseItemEvent$Start, $LivingEntityUseItemEvent$Stop, $LivingEntityUseItemEvent$Tick, $LivingEvent, $LivingShieldBlockEvent, $MobSpawnEvent } from "java:net/neoforged/neoforge/event/entity/living";
import { $AdvancementEvent, $AdvancementEvent$AdvancementEarnEvent, $ItemEntityPickupEvent, $ItemEntityPickupEvent$Post, $ItemEntityPickupEvent$Pre, $ItemTooltipEvent, $PlayerContainerEvent, $PlayerContainerEvent$Close, $PlayerContainerEvent$Open, $PlayerDestroyItemEvent, $PlayerEvent, $PlayerEvent$Clone, $PlayerEvent$ItemCraftedEvent, $PlayerEvent$ItemSmeltedEvent, $PlayerEvent$PlayerChangedDimensionEvent, $PlayerEvent$PlayerLoggedInEvent, $PlayerEvent$PlayerLoggedOutEvent, $PlayerEvent$PlayerRespawnEvent, $PlayerInteractEvent, $PlayerInteractEvent$EntityInteract, $PlayerInteractEvent$LeftClickBlock, $PlayerInteractEvent$LeftClickBlock$Action, $PlayerInteractEvent$RightClickBlock, $PlayerInteractEvent$RightClickItem } from "java:net/neoforged/neoforge/event/entity/player";
import { $BlockEvent, $BlockEvent$BlockToolModificationEvent, $BlockEvent$EntityMultiPlaceEvent, $BlockEvent$EntityPlaceEvent, $BlockEvent$FarmlandTrampleEvent, $BlockEvent$FluidPlaceBlockEvent, $BlockEvent$NeighborNotifyEvent, $BlockEvent$PortalSpawnEvent, $ChunkEvent, $ChunkEvent$Unload, $ExplosionEvent, $ExplosionEvent$Detonate, $ExplosionEvent$Start, $LevelEvent, $LevelEvent$Load, $LevelEvent$Save, $LevelEvent$Unload } from "java:net/neoforged/neoforge/event/level";
import { $ServerAboutToStartEvent, $ServerLifecycleEvent, $ServerStartedEvent, $ServerStartingEvent, $ServerStoppedEvent, $ServerStoppingEvent } from "java:net/neoforged/neoforge/event/server";
import { $EntityTickEvent, $EntityTickEvent$Post, $EntityTickEvent$Pre, $LevelTickEvent, $LevelTickEvent$Post, $LevelTickEvent$Pre, $PlayerTickEvent, $PlayerTickEvent$Post, $PlayerTickEvent$Pre, $ServerTickEvent, $ServerTickEvent$Post, $ServerTickEvent$Pre } from "java:net/neoforged/neoforge/event/tick";
import { $FluidStack, $FluidType, $FluidType$DripstoneDripInfo } from "java:net/neoforged/neoforge/fluids";
import { $FluidIngredient, $FluidIngredientType, $SizedFluidIngredient } from "java:net/neoforged/neoforge/fluids/crafting";
import { $IContainerFactory } from "java:net/neoforged/neoforge/network";
import { $PacketAndPayloadAcceptor } from "java:net/neoforged/neoforge/network/bundle";
import { $ConnectionType } from "java:net/neoforged/neoforge/network/connection";
import { $IRegistryExtension } from "java:net/neoforged/neoforge/registries";
import { $RegistryCallback } from "java:net/neoforged/neoforge/registries/callback";
import { $DataMapType, $DataMapType$Builder, $IWithData } from "java:net/neoforged/neoforge/registries/datamaps";
import { $ContextAwareReloadListener } from "java:net/neoforged/neoforge/resource";

declare module "@side-only/startup/events" {
}

export {};

declare global {
    namespace BlockEvents {
        function broken(handler: ((event: $BlockBrokenEventJS) => void)): void;
        function broken(extra: $Block, handler: ((event: $BlockBrokenEventJS) => void)): void;
        function entityPlaced(handler: ((event: $BlockEvent$EntityPlaceEvent) => void)): void;
        function entityPlaced(extra: $Block, handler: ((event: $BlockEvent$EntityPlaceEvent) => void)): void;
        function entityMultiPlaced(handler: ((event: $BlockEvent$EntityMultiPlaceEvent) => void)): void;
        function entityMultiPlaced(extra: $Block, handler: ((event: $BlockEvent$EntityMultiPlaceEvent) => void)): void;
        function neighborNotify(handler: ((event: $BlockEvent$NeighborNotifyEvent) => void)): void;
        function neighborNotify(extra: $Block, handler: ((event: $BlockEvent$NeighborNotifyEvent) => void)): void;
        function fluidPlaced(handler: ((event: $BlockEvent$FluidPlaceBlockEvent) => void)): void;
        function fluidPlaced(extra: $Block, handler: ((event: $BlockEvent$FluidPlaceBlockEvent) => void)): void;
        function farmlandTrample(handler: ((event: $BlockEvent$FarmlandTrampleEvent) => void)): void;
        function farmlandTrample(extra: $Block, handler: ((event: $BlockEvent$FarmlandTrampleEvent) => void)): void;
        function portalSpawn(handler: ((event: $BlockEvent$PortalSpawnEvent) => void)): void;
        function portalSpawn(extra: $Block, handler: ((event: $BlockEvent$PortalSpawnEvent) => void)): void;
        function toolModification(handler: ((event: $BlockEvent$BlockToolModificationEvent) => void)): void;
        function toolModification(extra: $Block, handler: ((event: $BlockEvent$BlockToolModificationEvent) => void)): void;
        function rightClicked(handler: ((event: $PlayerInteractEvent$RightClickBlock) => void)): void;
        function rightClicked(extra: $Block, handler: ((event: $PlayerInteractEvent$RightClickBlock) => void)): void;
        function placed(handler: ((event: $BlockEvent$EntityPlaceEvent) => void)): void;
        function placed(extra: $Block, handler: ((event: $BlockEvent$EntityPlaceEvent) => void)): void;
        function leftClicked(handler: ((event: $PlayerInteractEvent$LeftClickBlock) => void)): void;
        function leftClicked(extra: $Block, handler: ((event: $PlayerInteractEvent$LeftClickBlock) => void)): void;
        function randomTick(handler: ((event: $RandomTickEvent) => void)): void;
        function randomTick(extra: $Block, handler: ((event: $RandomTickEvent) => void)): void;
        function blockEntityTick(handler: ((event: $BlockEntityTickEvent) => void)): void;
        function blockEntityTick(extra: $BlockEntityType, handler: ((event: $BlockEntityTickEvent) => void)): void;
    }

    namespace CapabilityEvents {
        function register(handler: ((event: $CapabilityRegistryEventJS) => void)): void;
    }

    namespace ClientEvents {
        function tickPre(handler: ((event: $ClientTickEvent$Pre) => void)): void;
        function tickPost(handler: ((event: $ClientTickEvent$Post) => void)): void;
        function tick(handler: ((event: $ClientTickEvent$Post) => void)): void;
        function playerTickPre(handler: ((event: $PlayerTickEvent$Pre) => void)): void;
        function playerTickPost(handler: ((event: $PlayerTickEvent$Post) => void)): void;
        function interactionKey(handler: ((event: $InputEvent$InteractionKeyMappingTriggered) => void)): void;
        function loggedIn(handler: ((event: $ClientPlayerNetworkEvent$LoggingIn) => void)): void;
        function loggedOut(handler: ((event: $ClientPlayerNetworkEvent$LoggingOut) => void)): void;
        function cloned(handler: ((event: $ClientPlayerNetworkEvent$Clone) => void)): void;
        function commandRegistry(handler: ((event: $RegisterClientCommandsEvent) => void)): void;
        function registerKeyMappings(handler: ((event: $RegisterKeyMappingsEvent) => void)): void;
        function registerMenuScreens(handler: ((event: $RegisterMenuScreensEvent) => void)): void;
        function registerRenderers(handler: ((event: $EntityRenderersEvent$RegisterRenderers) => void)): void;
        function registerEntityRenderers(handler: ((event: $EntityRenderersEvent$RegisterRenderers) => void)): void;
        function registerBlockEntityRenderers(handler: ((event: $EntityRenderersEvent$RegisterRenderers) => void)): void;
        function registerParticleProviders(handler: ((event: $RegisterParticleProvidersEvent) => void)): void;
        function generateAssets(handler: ((event: $DataGeneratorJS) => void)): void;
        function generateAssets(extra: string, handler: ((event: $DataGeneratorJS) => void)): void;
        function lang(handler: ((event: $LangGeneratorJS) => void)): void;
        function lang(extra: string, handler: ((event: $LangGeneratorJS) => void)): void;
        function postEffects(handler: ((event: $PostEffectEventJS) => void)): void;
        function hud(handler: ((event: $PainterJS) => void)): void;
        function screenRender(handler: ((event: $ScreenRenderEventJS) => void)): void;
        function hudRender(handler: ((event: $Object) => void)): void;
        function worldRender(handler: ((event: $Object) => void)): void;
    }

    namespace CommandEvents {
        function register(handler: ((event: $RegisterCommandsEvent) => void)): void;
        function command(handler: ((event: $CommandEvent) => void)): void;
    }

    namespace EntityEvents {
        function damagePre(handler: ((event: $LivingDamageEvent$Pre) => void)): void;
        function damagePre(extra: $EntityType, handler: ((event: $LivingDamageEvent$Pre) => void)): void;
        function damagePost(handler: ((event: $LivingDamageEvent$Post) => void)): void;
        function damagePost(extra: $EntityType, handler: ((event: $LivingDamageEvent$Post) => void)): void;
        function death(handler: ((event: $LivingDeathEvent) => void)): void;
        function death(extra: $EntityType, handler: ((event: $LivingDeathEvent) => void)): void;
        function drops(handler: ((event: $LivingDropsEvent) => void)): void;
        function drops(extra: $EntityType, handler: ((event: $LivingDropsEvent) => void)): void;
        function finalizeSpawn(handler: ((event: $FinalizeSpawnEvent) => void)): void;
        function finalizeSpawn(extra: $EntityType, handler: ((event: $FinalizeSpawnEvent) => void)): void;
        function tickPre(handler: ((event: $EntityTickEvent$Pre) => void)): void;
        function tickPre(extra: $EntityType, handler: ((event: $EntityTickEvent$Pre) => void)): void;
        function tickPost(handler: ((event: $EntityTickEvent$Post) => void)): void;
        function tickPost(extra: $EntityType, handler: ((event: $EntityTickEvent$Post) => void)): void;
        function joinLevel(handler: ((event: $EntityJoinLevelEvent) => void)): void;
        function joinLevel(extra: $EntityType, handler: ((event: $EntityJoinLevelEvent) => void)): void;
        function leaveLevel(handler: ((event: $EntityLeaveLevelEvent) => void)): void;
        function leaveLevel(extra: $EntityType, handler: ((event: $EntityLeaveLevelEvent) => void)): void;
        function useItemStarted(handler: ((event: $LivingEntityUseItemEvent$Start) => void)): void;
        function useItemStarted(extra: $Item, handler: ((event: $LivingEntityUseItemEvent$Start) => void)): void;
        function useItemStopped(handler: ((event: $LivingEntityUseItemEvent$Stop) => void)): void;
        function useItemStopped(extra: $Item, handler: ((event: $LivingEntityUseItemEvent$Stop) => void)): void;
        function useItemFinished(handler: ((event: $LivingEntityUseItemEvent$Finish) => void)): void;
        function useItemFinished(extra: $Item, handler: ((event: $LivingEntityUseItemEvent$Finish) => void)): void;
        function useItemTick(handler: ((event: $LivingEntityUseItemEvent$Tick) => void)): void;
        function useItemTick(extra: $Item, handler: ((event: $LivingEntityUseItemEvent$Tick) => void)): void;
    }

    namespace GoalEvents {
        function register(handler: ((event: $GoalRegisterEventJS) => void)): void;
    }

    namespace ItemEvents {
        function rightClicked(handler: ((event: $PlayerInteractEvent$RightClickItem) => void)): void;
        function rightClicked(extra: $Item, handler: ((event: $PlayerInteractEvent$RightClickItem) => void)): void;
        function modification(handler: ((event: $ItemModificationEventJS) => void)): void;
        function tooltip(handler: ((event: $ItemTooltipEvent) => void)): void;
        function tooltip(extra: $Item, handler: ((event: $ItemTooltipEvent) => void)): void;
        function canPickUp(handler: ((event: $ItemEntityPickupEvent$Pre) => void)): void;
        function canPickUp(extra: $Item, handler: ((event: $ItemEntityPickupEvent$Pre) => void)): void;
        function pickedUpPre(handler: ((event: $ItemEntityPickupEvent$Pre) => void)): void;
        function pickedUpPre(extra: $Item, handler: ((event: $ItemEntityPickupEvent$Pre) => void)): void;
        function pickedUp(handler: ((event: $ItemEntityPickupEvent$Post) => void)): void;
        function pickedUp(extra: $Item, handler: ((event: $ItemEntityPickupEvent$Post) => void)): void;
        function dropped(handler: ((event: $ItemTossEvent) => void)): void;
        function dropped(extra: $Item, handler: ((event: $ItemTossEvent) => void)): void;
        function entityInteracted(handler: ((event: $PlayerInteractEvent$EntityInteract) => void)): void;
        function entityInteracted(extra: $Item, handler: ((event: $PlayerInteractEvent$EntityInteract) => void)): void;
        function foodEaten(handler: ((event: $LivingEntityUseItemEvent$Finish) => void)): void;
        function foodEaten(extra: $Item, handler: ((event: $LivingEntityUseItemEvent$Finish) => void)): void;
    }

    namespace LevelEvents {
        function loaded(handler: ((event: $LevelEvent$Load) => void)): void;
        function unloaded(handler: ((event: $LevelEvent$Unload) => void)): void;
        function saved(handler: ((event: $LevelEvent$Save) => void)): void;
        function tickPre(handler: ((event: $LevelTickEvent$Pre) => void)): void;
        function tickPost(handler: ((event: $LevelTickEvent$Post) => void)): void;
        function tick(handler: ((event: $LevelTickEvent$Post) => void)): void;
        function explosionStart(handler: ((event: $ExplosionEvent$Start) => void)): void;
        function beforeExplosion(handler: ((event: $ExplosionEvent$Start) => void)): void;
        function explosionDetonate(handler: ((event: $ExplosionEvent$Detonate) => void)): void;
        function afterExplosion(handler: ((event: $ExplosionEvent$Detonate) => void)): void;
    }

    namespace PlayerEvents {
        function loggedIn(handler: ((event: $PlayerEvent$PlayerLoggedInEvent) => void)): void;
        function loggedOut(handler: ((event: $PlayerEvent$PlayerLoggedOutEvent) => void)): void;
        function chat(handler: ((event: $ServerChatEvent) => void)): void;
        function tickPost(handler: ((event: $PlayerTickEvent$Post) => void)): void;
        function tickPre(handler: ((event: $PlayerTickEvent$Pre) => void)): void;
        function cloned(handler: ((event: $PlayerEvent$Clone) => void)): void;
        function respawned(handler: ((event: $PlayerEvent$PlayerRespawnEvent) => void)): void;
        function changedDimension(handler: ((event: $PlayerEvent$PlayerChangedDimensionEvent) => void)): void;
        function advancement(handler: ((event: $AdvancementEvent$AdvancementEarnEvent) => void)): void;
        function containerOpened(handler: ((event: $PlayerContainerEvent$Open) => void)): void;
        function inventoryOpened(handler: ((event: $PlayerContainerEvent$Open) => void)): void;
        function containerClosed(handler: ((event: $PlayerContainerEvent$Close) => void)): void;
        function inventoryClosed(handler: ((event: $PlayerContainerEvent$Close) => void)): void;
        function entityInteract(handler: ((event: $PlayerInteractEvent$EntityInteract) => void)): void;
        function crafted(handler: ((event: $PlayerEvent$ItemCraftedEvent) => void)): void;
        function crafted(extra: $Item, handler: ((event: $PlayerEvent$ItemCraftedEvent) => void)): void;
        function smelted(handler: ((event: $PlayerEvent$ItemSmeltedEvent) => void)): void;
        function smelted(extra: $Item, handler: ((event: $PlayerEvent$ItemSmeltedEvent) => void)): void;
        function destroyed(handler: ((event: $PlayerDestroyItemEvent) => void)): void;
        function destroyed(extra: $Item, handler: ((event: $PlayerDestroyItemEvent) => void)): void;
        function inventoryChanged(handler: ((event: $InventoryChangedEventJS) => void)): void;
        function inventoryChanged(extra: $Item, handler: ((event: $InventoryChangedEventJS) => void)): void;
    }

    namespace RecipeViewerEvents {
        function addEntries(handler: ((event: $RecipeViewerEntryListJS) => void)): void;
        function addEntries(extra: string, handler: ((event: $RecipeViewerEntryListJS) => void)): void;
        function removeEntries(handler: ((event: $RecipeViewerEntryListJS) => void)): void;
        function removeEntries(extra: string, handler: ((event: $RecipeViewerEntryListJS) => void)): void;
        function removeRecipes(handler: ((event: $RecipeViewerRecipeListJS) => void)): void;
        function removeCategories(handler: ((event: $RecipeViewerCategoryListJS) => void)): void;
        function addInformation(handler: ((event: $RecipeViewerInformationJS) => void)): void;
    }

    namespace ServerEvents {
        function tickPre(handler: ((event: $ServerTickEvent$Pre) => void)): void;
        function tickPost(handler: ((event: $ServerTickEvent$Post) => void)): void;
        function recipes(handler: ((event: $RecipeEventJS) => void)): void;
        function afterRecipes(handler: ((event: $RecipeEventJS) => void)): void;
        function generateData(handler: ((event: $DataGeneratorJS) => void)): void;
        function generateData(extra: string, handler: ((event: $DataGeneratorJS) => void)): void;
        function aboutToStart(handler: ((event: $ServerAboutToStartEvent) => void)): void;
        function starting(handler: ((event: $ServerStartingEvent) => void)): void;
        function started(handler: ((event: $ServerStartedEvent) => void)): void;
        function stopping(handler: ((event: $ServerStoppingEvent) => void)): void;
        function stopped(handler: ((event: $ServerStoppedEvent) => void)): void;
        function datapackSync(handler: ((event: $OnDatapackSyncEvent) => void)): void;
        function tagsUpdated(handler: ((event: $TagsUpdatedEvent) => void)): void;
        function lootTableLoad(handler: ((event: $LootTableLoadEvent) => void)): void;
        function lootTables(handler: ((event: $LootTableEventJS) => void)): void;
        function tags(handler: ((event: $TagEventJS) => void)): void;
        function tags(extra: $ResourceLocation, handler: ((event: $TagEventJS) => void)): void;
        function tradeDeclaration(handler: ((event: $VillagerTradeDeclarationEventJS) => void)): void;
        function tradeReload(handler: ((event: $VillagerTradeReloadEventJS) => void)): void;
    }

}
