// Auto-generated by NekoJS probe. Derived from RegistryBuilderContract reflection over the builder classes (ticket 15).
// Do not edit; regenerate with /nekojs probe.

/** BlockBuilder — registry 'minecraft:block', type 'basic', sugar 'block'. */
interface BlockBuilder {
    hardness: number;
    readonly id: any;
    item: any;
    lightLevel: number;
    mapColor: string;
    noItem(): void;
    renderType: string;
    requiresTool: boolean;
    resistance: number;
    setHardness(hardness: number): void;
    setItem(item: any): void;
    setLightLevel(lightLevel: number): void;
    setMapColor(mapColor: string): void;
    setRenderType(renderType: string): void;
    setRequiresTool(requiresTool: boolean): void;
    setResistance(resistance: number): void;
    setSound(sound: string): void;
    sound: string;
    unbreakable(): void;
}

/** CreativeTabBuilder — registry 'minecraft:creative_mode_tab', type 'basic', sugar 'creativeModeTab'. */
interface CreativeTabBuilder {
    add(item: any): void;
    icon: any;
    readonly id: any;
    setIcon(icon: any): void;
    setTitle(title: string): void;
    title: string;
}

/** EnchantmentBuilder — registry 'minecraft:enchantment', type 'basic', sugar 'enchantment'. */
interface EnchantmentBuilder {
    anvilCost: number;
    readonly id: any;
    maxCostBase: number;
    maxCostPerLevel: number;
    maxLevel: number;
    minCostBase: number;
    minCostPerLevel: number;
    setAnvilCost(anvilCost: number): void;
    setMaxCostBase(maxCostBase: number): void;
    setMaxCostPerLevel(maxCostPerLevel: number): void;
    setMaxLevel(maxLevel: number): void;
    setMinCostBase(minCostBase: number): void;
    setMinCostPerLevel(minCostPerLevel: number): void;
    setSlots(slots: string): void;
    setSupportedItems(supportedItems: string): void;
    setWeight(weight: number): void;
    slots: string;
    supportedItems: string;
    weight: number;
}

/** EntityTypeBuilder — registry 'minecraft:entity_type', type 'basic', sugar 'entityType'. */
interface EntityTypeBuilder {
    attributes(consumer: (b: any) => void): void;
    category: string;
    fireImmune: boolean;
    goals(consumer: (b: any) => void): void;
    height: number;
    readonly id: any;
    noSave: boolean;
    noSummon: boolean;
    receiveVelocityUpdates: boolean;
    setCategory(category: string): void;
    setFireImmune(fireImmune: boolean): void;
    setHeight(height: number): void;
    setNoSave(noSave: boolean): void;
    setNoSummon(noSummon: boolean): void;
    setReceiveVelocityUpdates(receiveVelocityUpdates: boolean): void;
    setTrackingRange(trackingRange: number): void;
    setUpdateInterval(updateInterval: number): void;
    setWidth(width: number): void;
    size(width: number, height: number): void;
    spawnEgg(backgroundColor: number, highlightColor: number): void;
    readonly spawnEggId: any;
    trackingRange: number;
    updateInterval: number;
    width: number;
}

/** ItemBuilder — registry 'minecraft:item', type 'basic', sugar 'item'. */
interface ItemBuilder {
    burnTime: number;
    fireResistant: boolean;
    food(consumer: (b: any) => void): void;
    glowing: boolean;
    groupTab: string;
    readonly id: any;
    maxDamage: number;
    maxStackSize: number;
    rarity: string;
    setBurnTime(burnTime: number): void;
    setFireResistant(fireResistant: boolean): void;
    setGlowing(glowing: boolean): void;
    setGroupTab(groupTab: string): void;
    setMaxDamage(maxDamage: number): void;
    setMaxStackSize(maxStackSize: number): void;
    setRarity(rarity: string): void;
}

/** MobEffectBuilder — registry 'minecraft:mob_effect', type 'basic', sugar 'mobEffect'. */
interface MobEffectBuilder {
    category: string;
    color: number;
    readonly id: any;
    setCategory(category: string): void;
    setColor(color: number): void;
}

/** PaintingVariantBuilder — registry 'minecraft:painting_variant', type 'basic', sugar 'paintingVariant'. */
interface PaintingVariantBuilder {
    assetId: string;
    height: number;
    readonly id: any;
    setAssetId(assetId: string): void;
    setHeight(height: number): void;
    setWidth(width: number): void;
    width: number;
}

/** ParticleTypeBuilder — registry 'minecraft:particle_type', type 'basic', sugar 'particleType'. */
interface ParticleTypeBuilder {
    readonly id: any;
    overrideLimiter: boolean;
    setOverrideLimiter(overrideLimiter: boolean): void;
}

/** PotionBuilder — registry 'minecraft:potion', type 'basic', sugar 'potion'. */
interface PotionBuilder {
    effect(effect: any, durationTicks: number, amplifier: number, ambient: boolean, visible: boolean): void;
    readonly id: any;
}

/** SoundEventBuilder — registry 'minecraft:sound_event', type 'basic', sugar 'soundEvent'. */
interface SoundEventBuilder {
    fixedRange: number;
    readonly id: any;
    setFixedRange(fixedRange: number): void;
}

/** VillagerTypeBuilder — registry 'minecraft:villager_type', type 'basic', sugar 'villagerType'. */
interface VillagerTypeBuilder {
    readonly id: any;
}

