// Auto-generated by NekoJS probe. Derived from RegistryBuilderContract reflection over the builder classes (ticket 15).
// Do not edit; regenerate with /nekojs probe.

/** DynamicItemBuilder — registry 'minecraft:item', type 'dynamic', sugar 'item'. */
interface DynamicItemBuilder {
    fireResistant: boolean;
    maxStackSize: number;
    mode: string;
    rarity: string;
    setFireResistant(value: boolean): DynamicItemBuilder;
    setMaxStackSize(size: number): DynamicItemBuilder;
    setMode(mode: string): any;
    setRarity(rarity: string): DynamicItemBuilder;
}

/** DynamicMobEffectBuilder — registry 'minecraft:mob_effect', type 'dynamic', sugar 'mobEffect'. */
interface DynamicMobEffectBuilder {
    category: string;
    color: number;
    mode: string;
    setCategory(category: string): DynamicMobEffectBuilder;
    setColor(color: number): DynamicMobEffectBuilder;
    setMode(mode: string): any;
}

/** DynamicSoundEventBuilder — registry 'minecraft:sound_event', type 'dynamic', sugar 'soundEvent'. */
interface DynamicSoundEventBuilder {
    fixedRange: number;
    mode: string;
    setFixedRange(range: number): DynamicSoundEventBuilder;
    setMode(mode: string): any;
}

