










        alignedSlice(arg0: number): $ByteBuffer;
        alignmentOffset(arg0: number, arg1: number): number;
        append(arg0: $CharSequence): $Appendable;
        append(arg0: $CharSequence): $CharBuffer;
        append(arg0: $CharSequence, arg1: number, arg2: number): $Appendable;
        append(arg0: $CharSequence, arg1: number, arg2: number): $CharBuffer;
        append(arg0: string): $Appendable;
        append(arg0: string): $CharBuffer;
        array(): number[];
        array(): number[];
        array(): number[];
        array(): number[];
        array(): number[];
        array(): number[];
        array(): object;
        array(): object;
        array(): object;
        array(): object;
        array(): object;
        array(): object;
        array(): object;
        array(): object;
        array(): string[];
        arrayOffset(): number;
        arrayOffset(): number;
        arrayOffset(): number;
        arrayOffset(): number;
        arrayOffset(): number;
        arrayOffset(): number;
        arrayOffset(): number;
        arrayOffset(): number;
        asCharBuffer(): $CharBuffer;
        asDoubleBuffer(): $DoubleBuffer;
        asFloatBuffer(): $FloatBuffer;
        asIntBuffer(): $IntBuffer;
        asLongBuffer(): $LongBuffer;
        asReadOnlyBuffer(): $ByteBuffer;
        asReadOnlyBuffer(): $CharBuffer;
        asReadOnlyBuffer(): $DoubleBuffer;
        asReadOnlyBuffer(): $FloatBuffer;
        asReadOnlyBuffer(): $IntBuffer;
        asReadOnlyBuffer(): $LongBuffer;
        asReadOnlyBuffer(): $ShortBuffer;
        asShortBuffer(): $ShortBuffer;
        capacity(): number;
        charAt(arg0: number): string;
        chars(): $IntStream;
        clear(): $Buffer;
        clear(): $Buffer;
        clear(): $Buffer;
        clear(): $Buffer;
        clear(): $Buffer;
        clear(): $Buffer;
        clear(): $Buffer;
        clear(): $Buffer;
        clear(): $ByteBuffer;
        clear(): $CharBuffer;
        clear(): $DoubleBuffer;
        clear(): $FloatBuffer;
        clear(): $IntBuffer;
        clear(): $LongBuffer;
        clear(): $ShortBuffer;
        compact(): $ByteBuffer;
        compact(): $CharBuffer;
        compact(): $DoubleBuffer;
        compact(): $FloatBuffer;
        compact(): $IntBuffer;
        compact(): $LongBuffer;
        compact(): $ShortBuffer;
        compareTo(arg0: $ByteBuffer): number;
        compareTo(arg0: $CharBuffer): number;
        compareTo(arg0: $DoubleBuffer): number;
        compareTo(arg0: $FloatBuffer): number;
        compareTo(arg0: $IntBuffer): number;
        compareTo(arg0: $LongBuffer): number;
        compareTo(arg0: $ShortBuffer): number;
        compareTo(arg0: object): number;
        compareTo(arg0: object): number;
        compareTo(arg0: object): number;
        compareTo(arg0: object): number;
        compareTo(arg0: object): number;
        compareTo(arg0: object): number;
        compareTo(arg0: object): number;
        duplicate(): $Buffer;
        duplicate(): $Buffer;
        duplicate(): $Buffer;
        duplicate(): $Buffer;
        duplicate(): $Buffer;
        duplicate(): $Buffer;
        duplicate(): $Buffer;
        duplicate(): $Buffer;
        duplicate(): $ByteBuffer;
        duplicate(): $CharBuffer;
        duplicate(): $DoubleBuffer;
        duplicate(): $FloatBuffer;
        duplicate(): $IntBuffer;
        duplicate(): $LongBuffer;
        duplicate(): $ShortBuffer;
        equals(arg0: object): boolean;
        equals(arg0: object): boolean;
        equals(arg0: object): boolean;
        equals(arg0: object): boolean;
        equals(arg0: object): boolean;
        equals(arg0: object): boolean;
        equals(arg0: object): boolean;
        flip(): $Buffer;
        flip(): $Buffer;
        flip(): $Buffer;
        flip(): $Buffer;
        flip(): $Buffer;
        flip(): $Buffer;
        flip(): $Buffer;
        flip(): $Buffer;
        flip(): $ByteBuffer;
        flip(): $CharBuffer;
        flip(): $DoubleBuffer;
        flip(): $FloatBuffer;
        flip(): $IntBuffer;
        flip(): $LongBuffer;
        flip(): $ShortBuffer;
        get char(): string;
        get direct(): boolean;
        get direct(): boolean;
        get direct(): boolean;
        get direct(): boolean;
        get direct(): boolean;
        get direct(): boolean;
        get direct(): boolean;
        get direct(): boolean;
        get double(): number;
        get empty(): boolean;
        get float(): number;
        get int(): number;
        get long(): number;
        get readOnly(): boolean;
        get short(): number;
        get(): number;
        get(): number;
        get(): number;
        get(): number;
        get(): number;
        get(): number;
        get(): string;
        get(arg0: number): number;
        get(arg0: number): number;
        get(arg0: number): number;
        get(arg0: number): number;
        get(arg0: number): number;
        get(arg0: number): number;
        get(arg0: number): string;
        get(arg0: number, arg1: number[]): $ByteBuffer;
        get(arg0: number, arg1: number[]): $DoubleBuffer;
        get(arg0: number, arg1: number[]): $FloatBuffer;
        get(arg0: number, arg1: number[]): $IntBuffer;
        get(arg0: number, arg1: number[]): $LongBuffer;
        get(arg0: number, arg1: number[]): $ShortBuffer;
        get(arg0: number, arg1: number[], arg2: number, arg3: number): $ByteBuffer;
        get(arg0: number, arg1: number[], arg2: number, arg3: number): $DoubleBuffer;
        get(arg0: number, arg1: number[], arg2: number, arg3: number): $FloatBuffer;
        get(arg0: number, arg1: number[], arg2: number, arg3: number): $IntBuffer;
        get(arg0: number, arg1: number[], arg2: number, arg3: number): $LongBuffer;
        get(arg0: number, arg1: number[], arg2: number, arg3: number): $ShortBuffer;
        get(arg0: number, arg1: string[]): $CharBuffer;
        get(arg0: number, arg1: string[], arg2: number, arg3: number): $CharBuffer;
        get(arg0: number[]): $ByteBuffer;
        get(arg0: number[]): $DoubleBuffer;
        get(arg0: number[]): $FloatBuffer;
        get(arg0: number[]): $IntBuffer;
        get(arg0: number[]): $LongBuffer;
        get(arg0: number[]): $ShortBuffer;
        get(arg0: number[], arg1: number, arg2: number): $ByteBuffer;
        get(arg0: number[], arg1: number, arg2: number): $DoubleBuffer;
        get(arg0: number[], arg1: number, arg2: number): $FloatBuffer;
        get(arg0: number[], arg1: number, arg2: number): $IntBuffer;
        get(arg0: number[], arg1: number, arg2: number): $LongBuffer;
        get(arg0: number[], arg1: number, arg2: number): $ShortBuffer;
        get(arg0: string[]): $CharBuffer;
        get(arg0: string[], arg1: number, arg2: number): $CharBuffer;
        getChar(): string;
        getChar(arg0: number): string;
        getDouble(): number;
        getDouble(arg0: number): number;
        getFloat(): number;
        getFloat(arg0: number): number;
        getInt(): number;
        getInt(arg0: number): number;
        getLong(): number;
        getLong(arg0: number): number;
        getShort(): number;
        getShort(arg0: number): number;
        hasArray(): boolean;
        hasArray(): boolean;
        hasArray(): boolean;
        hasArray(): boolean;
        hasArray(): boolean;
        hasArray(): boolean;
        hasArray(): boolean;
        hasArray(): boolean;
        hasRemaining(): boolean;
        hashCode(): number;
        hashCode(): number;
        hashCode(): number;
        hashCode(): number;
        hashCode(): number;
        hashCode(): number;
        hashCode(): number;
        isDirect(): boolean;
        isDirect(): boolean;
        isDirect(): boolean;
        isDirect(): boolean;
        isDirect(): boolean;
        isDirect(): boolean;
        isDirect(): boolean;
        isDirect(): boolean;
        isEmpty(): boolean;
        isReadOnly(): boolean;
        length(): number;
        limit(): number;
        limit(arg0: number): $Buffer;
        limit(arg0: number): $Buffer;
        limit(arg0: number): $Buffer;
        limit(arg0: number): $Buffer;
        limit(arg0: number): $Buffer;
        limit(arg0: number): $Buffer;
        limit(arg0: number): $Buffer;
        limit(arg0: number): $Buffer;
        limit(arg0: number): $ByteBuffer;
        limit(arg0: number): $CharBuffer;
        limit(arg0: number): $DoubleBuffer;
        limit(arg0: number): $FloatBuffer;
        limit(arg0: number): $IntBuffer;
        limit(arg0: number): $LongBuffer;
        limit(arg0: number): $ShortBuffer;
        mark(): $Buffer;
        mark(): $Buffer;
        mark(): $Buffer;
        mark(): $Buffer;
        mark(): $Buffer;
        mark(): $Buffer;
        mark(): $Buffer;
        mark(): $Buffer;
        mark(): $ByteBuffer;
        mark(): $CharBuffer;
        mark(): $DoubleBuffer;
        mark(): $FloatBuffer;
        mark(): $IntBuffer;
        mark(): $LongBuffer;
        mark(): $ShortBuffer;
        mismatch(arg0: $ByteBuffer): number;
        mismatch(arg0: $CharBuffer): number;
        mismatch(arg0: $DoubleBuffer): number;
        mismatch(arg0: $FloatBuffer): number;
        mismatch(arg0: $IntBuffer): number;
        mismatch(arg0: $LongBuffer): number;
        mismatch(arg0: $ShortBuffer): number;
        order(): $ByteOrder;
        order(): $ByteOrder;
        order(): $ByteOrder;
        order(): $ByteOrder;
        order(): $ByteOrder;
        order(): $ByteOrder;
        order(): $ByteOrder;
        order(arg0: $ByteOrder): $ByteBuffer;
        position(): number;
        position(arg0: number): $Buffer;
        position(arg0: number): $Buffer;
        position(arg0: number): $Buffer;
        position(arg0: number): $Buffer;
        position(arg0: number): $Buffer;
        position(arg0: number): $Buffer;
        position(arg0: number): $Buffer;
        position(arg0: number): $Buffer;
        position(arg0: number): $ByteBuffer;
        position(arg0: number): $CharBuffer;
        position(arg0: number): $DoubleBuffer;
        position(arg0: number): $FloatBuffer;
        position(arg0: number): $IntBuffer;
        position(arg0: number): $LongBuffer;
        position(arg0: number): $ShortBuffer;
        put(arg0: $ByteBuffer): $ByteBuffer;
        put(arg0: $CharBuffer): $CharBuffer;
        put(arg0: $DoubleBuffer): $DoubleBuffer;
        put(arg0: $FloatBuffer): $FloatBuffer;
        put(arg0: $IntBuffer): $IntBuffer;
        put(arg0: $LongBuffer): $LongBuffer;
        put(arg0: $ShortBuffer): $ShortBuffer;
        put(arg0: number): $ByteBuffer;
        put(arg0: number): $DoubleBuffer;
        put(arg0: number): $FloatBuffer;
        put(arg0: number): $IntBuffer;
        put(arg0: number): $LongBuffer;
        put(arg0: number): $ShortBuffer;
        put(arg0: number, arg1: $ByteBuffer, arg2: number, arg3: number): $ByteBuffer;
        put(arg0: number, arg1: $CharBuffer, arg2: number, arg3: number): $CharBuffer;
        put(arg0: number, arg1: $DoubleBuffer, arg2: number, arg3: number): $DoubleBuffer;
        put(arg0: number, arg1: $FloatBuffer, arg2: number, arg3: number): $FloatBuffer;
        put(arg0: number, arg1: $IntBuffer, arg2: number, arg3: number): $IntBuffer;
        put(arg0: number, arg1: $LongBuffer, arg2: number, arg3: number): $LongBuffer;
        put(arg0: number, arg1: $ShortBuffer, arg2: number, arg3: number): $ShortBuffer;
        put(arg0: number, arg1: number): $ByteBuffer;
        put(arg0: number, arg1: number): $DoubleBuffer;
        put(arg0: number, arg1: number): $FloatBuffer;
        put(arg0: number, arg1: number): $IntBuffer;
        put(arg0: number, arg1: number): $LongBuffer;
        put(arg0: number, arg1: number): $ShortBuffer;
        put(arg0: number, arg1: number[]): $ByteBuffer;
        put(arg0: number, arg1: number[]): $DoubleBuffer;
        put(arg0: number, arg1: number[]): $FloatBuffer;
        put(arg0: number, arg1: number[]): $IntBuffer;
        put(arg0: number, arg1: number[]): $LongBuffer;
        put(arg0: number, arg1: number[]): $ShortBuffer;
        put(arg0: number, arg1: number[], arg2: number, arg3: number): $ByteBuffer;
        put(arg0: number, arg1: number[], arg2: number, arg3: number): $DoubleBuffer;
        put(arg0: number, arg1: number[], arg2: number, arg3: number): $FloatBuffer;
        put(arg0: number, arg1: number[], arg2: number, arg3: number): $IntBuffer;
        put(arg0: number, arg1: number[], arg2: number, arg3: number): $LongBuffer;
        put(arg0: number, arg1: number[], arg2: number, arg3: number): $ShortBuffer;
        put(arg0: number, arg1: string): $CharBuffer;
        put(arg0: number, arg1: string[]): $CharBuffer;
        put(arg0: number, arg1: string[], arg2: number, arg3: number): $CharBuffer;
        put(arg0: number[]): $ByteBuffer;
        put(arg0: number[]): $DoubleBuffer;
        put(arg0: number[]): $FloatBuffer;
        put(arg0: number[]): $IntBuffer;
        put(arg0: number[]): $LongBuffer;
        put(arg0: number[]): $ShortBuffer;
        put(arg0: number[], arg1: number, arg2: number): $ByteBuffer;
        put(arg0: number[], arg1: number, arg2: number): $DoubleBuffer;
        put(arg0: number[], arg1: number, arg2: number): $FloatBuffer;
        put(arg0: number[], arg1: number, arg2: number): $IntBuffer;
        put(arg0: number[], arg1: number, arg2: number): $LongBuffer;
        put(arg0: number[], arg1: number, arg2: number): $ShortBuffer;
        put(arg0: string): $CharBuffer;
        put(arg0: string): $CharBuffer;
        put(arg0: string, arg1: number, arg2: number): $CharBuffer;
        put(arg0: string[]): $CharBuffer;
        put(arg0: string[], arg1: number, arg2: number): $CharBuffer;
        putChar(arg0: number, arg1: string): $ByteBuffer;
        putChar(arg0: string): $ByteBuffer;
        putDouble(arg0: number): $ByteBuffer;
        putDouble(arg0: number, arg1: number): $ByteBuffer;
        putFloat(arg0: number): $ByteBuffer;
        putFloat(arg0: number, arg1: number): $ByteBuffer;
        putInt(arg0: number): $ByteBuffer;
        putInt(arg0: number, arg1: number): $ByteBuffer;
        putLong(arg0: number): $ByteBuffer;
        putLong(arg0: number, arg1: number): $ByteBuffer;
        putShort(arg0: number): $ByteBuffer;
        putShort(arg0: number, arg1: number): $ByteBuffer;
        read(arg0: $CharBuffer): number;
        remaining(): number;
        reset(): $Buffer;
        reset(): $Buffer;
        reset(): $Buffer;
        reset(): $Buffer;
        reset(): $Buffer;
        reset(): $Buffer;
        reset(): $Buffer;
        reset(): $Buffer;
        reset(): $ByteBuffer;
        reset(): $CharBuffer;
        reset(): $DoubleBuffer;
        reset(): $FloatBuffer;
        reset(): $IntBuffer;
        reset(): $LongBuffer;
        reset(): $ShortBuffer;
        rewind(): $Buffer;
        rewind(): $Buffer;
        rewind(): $Buffer;
        rewind(): $Buffer;
        rewind(): $Buffer;
        rewind(): $Buffer;
        rewind(): $Buffer;
        rewind(): $Buffer;
        rewind(): $ByteBuffer;
        rewind(): $CharBuffer;
        rewind(): $DoubleBuffer;
        rewind(): $FloatBuffer;
        rewind(): $IntBuffer;
        rewind(): $LongBuffer;
        rewind(): $ShortBuffer;
        slice(): $Buffer;
        slice(): $Buffer;
        slice(): $Buffer;
        slice(): $Buffer;
        slice(): $Buffer;
        slice(): $Buffer;
        slice(): $Buffer;
        slice(): $Buffer;
        slice(): $ByteBuffer;
        slice(): $CharBuffer;
        slice(): $DoubleBuffer;
        slice(): $FloatBuffer;
        slice(): $IntBuffer;
        slice(): $LongBuffer;
        slice(): $ShortBuffer;
        slice(arg0: number, arg1: number): $Buffer;
        slice(arg0: number, arg1: number): $Buffer;
        slice(arg0: number, arg1: number): $Buffer;
        slice(arg0: number, arg1: number): $Buffer;
        slice(arg0: number, arg1: number): $Buffer;
        slice(arg0: number, arg1: number): $Buffer;
        slice(arg0: number, arg1: number): $Buffer;
        slice(arg0: number, arg1: number): $Buffer;
        slice(arg0: number, arg1: number): $ByteBuffer;
        slice(arg0: number, arg1: number): $CharBuffer;
        slice(arg0: number, arg1: number): $DoubleBuffer;
        slice(arg0: number, arg1: number): $FloatBuffer;
        slice(arg0: number, arg1: number): $IntBuffer;
        slice(arg0: number, arg1: number): $LongBuffer;
        slice(arg0: number, arg1: number): $ShortBuffer;
        static BIG_ENDIAN: $ByteOrder;
        static LITTLE_ENDIAN: $ByteOrder;
        static allocate(arg0: number): $ByteBuffer;
        static allocate(arg0: number): $CharBuffer;
        static allocate(arg0: number): $DoubleBuffer;
        static allocate(arg0: number): $FloatBuffer;
        static allocate(arg0: number): $IntBuffer;
        static allocate(arg0: number): $LongBuffer;
        static allocate(arg0: number): $ShortBuffer;
        static allocateDirect(arg0: number): $ByteBuffer;
        static nativeOrder(): $ByteOrder;
        static wrap(arg0: $CharSequence): $CharBuffer;
        static wrap(arg0: $CharSequence, arg1: number, arg2: number): $CharBuffer;
        static wrap(arg0: number[]): $ByteBuffer;
        static wrap(arg0: number[]): $DoubleBuffer;
        static wrap(arg0: number[]): $FloatBuffer;
        static wrap(arg0: number[]): $IntBuffer;
        static wrap(arg0: number[]): $LongBuffer;
        static wrap(arg0: number[]): $ShortBuffer;
        static wrap(arg0: number[], arg1: number, arg2: number): $ByteBuffer;
        static wrap(arg0: number[], arg1: number, arg2: number): $DoubleBuffer;
        static wrap(arg0: number[], arg1: number, arg2: number): $FloatBuffer;
        static wrap(arg0: number[], arg1: number, arg2: number): $IntBuffer;
        static wrap(arg0: number[], arg1: number, arg2: number): $LongBuffer;
        static wrap(arg0: number[], arg1: number, arg2: number): $ShortBuffer;
        static wrap(arg0: string[]): $CharBuffer;
        static wrap(arg0: string[], arg1: number, arg2: number): $CharBuffer;
        subSequence(arg0: number, arg1: number): $CharBuffer;
        subSequence(arg0: number, arg1: number): $CharSequence;
        toString(): string;
        toString(): string;
        toString(): string;
        toString(): string;
        toString(): string;
        toString(): string;
        toString(): string;
        toString(): string;
    export class $Buffer {
    export class $ByteBuffer extends $Buffer implements $Comparable {
    export class $ByteOrder {
    export class $CharBuffer extends $Buffer implements $Comparable, $Appendable, $CharSequence, $Readable {
    export class $DoubleBuffer extends $Buffer implements $Comparable {
    export class $FloatBuffer extends $Buffer implements $Comparable {
    export class $IntBuffer extends $Buffer implements $Comparable {
    export class $LongBuffer extends $Buffer implements $Comparable {
    export class $ShortBuffer extends $Buffer implements $Comparable {
    }
    }
    }
    }
    }
    }
    }
    }
    }
declare module "java:java/nio" {
export * as charset from "java:java/nio/charset";
import { $Appendable, $CharSequence, $Comparable, $Readable, $String } from "java:java/lang";
import { $IntStream } from "java:java/util/stream";
}