package com.tkisor.nekojs.probe.backend.typescript;

import com.tkisor.nekojs.api.catalog.RegistryBuilderSurfaceEntry;

import java.util.List;

/**
 * typed Builder 契约条目 → TS 声明（ticket 15，AC9）。
 * 输入是 {@link RegistryBuilderSurfaceEntry}（版本树契约反射派生）；Python 侧
 * {@code RegistryBuilderPyRenderer} 从<b>同一</b>条目列表渲染，成员语义两侧一致。
 * {@link TypeScriptProbeBackend} 与 contract/golden 测试共用本渲染器。
 */
public final class RegistryBuilderTsRenderer {

    private RegistryBuilderTsRenderer() {}

    /** 渲染 {@code @registry-builders/index.d.ts} 内容；空列表返回空串。 */
    public static String render(List<RegistryBuilderSurfaceEntry> entries) {
        if (entries == null || entries.isEmpty()) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        sb.append("// Auto-generated by NekoJS probe. Derived from RegistryBuilderContract reflection over the builder classes (ticket 15).\n");
        sb.append("// Do not edit; regenerate with /nekojs probe.\n\n");
        for (RegistryBuilderSurfaceEntry entry : entries) {
            sb.append("/** ").append(entry.builderName())
                    .append(" — registry '").append(entry.registryKey()).append('\'')
                    .append(", type '").append(entry.typeName()).append('\'');
            if (entry.sugarName() != null && !entry.sugarName().isEmpty()) {
                sb.append(", sugar '").append(entry.sugarName()).append('\'');
            }
            sb.append(". */\n");
            sb.append("interface ").append(entry.builderName()).append(" {\n");
            for (RegistryBuilderSurfaceEntry.Member member : entry.members()) {
                switch (member.kind()) {
                    case WRITABLE_PROPERTY -> sb.append("    ").append(member.name()).append(": ")
                            .append(member.tsType()).append(";\n");
                    case READ_ONLY_PROPERTY -> sb.append("    readonly ").append(member.name()).append(": ")
                            .append(member.tsType()).append(";\n");
                    case METHOD -> sb.append("    ").append(member.tsType()).append(";\n");
                }
            }
            sb.append("}\n\n");
        }
        return sb.toString();
    }
}
